### ISSUE TITLE
Material Design > Layout > Bring in the new Roboto

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#294]
We need to update Roboto Condensed to the new Roboto. We've got a check-in of the former so we'll need to update to the latter and change any of the `font-family` references as needed.

http://www.google.com/design/spec/style/typography.html#typography-roboto

<img src="http://1.bp.blogspot.com/-iJ1hNsX_OZA/U8arJjPub5I/AAAAAAAAOgQ/tC7esCJKLHk/s1600/the_new_roboto1.png" width="500px">

**Comment by addyosmani** [comment]
To the best of my knowledge the above is the correct new Roboto. https://github.com/Polymer/font-roboto definitely is. We're using the correct version afaik in our material-sprint branch now.

**Comment by martinduparc** [comment]
Thanks for the update @addyosmani
