### ISSUE TITLE
Material Design > Components

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#296]
To give developers targeting older browsers and simple sites a path to using [Material Design](http://google.com/design/spec), we're going to implement an official light-weight version using just JavaScript and CSS.

These will strive to be simple enough that anyone can easily customise them. For evergreen browsers, we recommend just using Polymer directly where possible.

**This is a preliminary list we hope to ship:**

* Button ([spec](http://www.google.com/design/spec/components/buttons.html#))
* Radio button
* Input ([spec](http://www.google.com/design/spec/components/text-fields.html))
* Toolbar
* Card ([spec](http://www.google.com/design/spec/components/cards.html))
* Progress bar
* Slider ([spec](http://www.google.com/design/spec/components/sliders.html))
* Icon button
* Fab
* Shadow
* Toggle
* Toolbar
* Menu button ([spec](http://www.google.com/design/spec/components/menus.html))

**Who is working on what?**

| Element          | Author          | Prototype   |
| ------------- | ------------- | ------------- |
| Button          | @addyosmani      | http://codepen.io/addyosmani/pen/Cjlaz |
| Input fields           | @mattcooper      | http://codepen.io/mattcooper/pen/jmIua |
| Radio button          | @Itrulia       | http://jsfiddle.net/itrulia/25pj2/ |
| Icon button   | Unassigned      | |
| Checkbox          | @jasonmayes        | http://codepen.io/jasonmayes/pen/wxtFr |
| Shadow & Cards           | @addyosmani       | http://codepen.io/addyosmani/pen/zimes |
| Toggle button | @mattcooper  | http://codepen.io/mattcooper/pen/npEyu |
| Progress        | @marcacohen      | |
| Slider        | @devnook      | https://github.com/google/web-starter-kit/pull/334 |
| FAB button           | @wibblymat | http://codepen.io/wibblymat/pen/mnGsu |
| Menu button    | @nicolasgarnier | |
| Theming | @devnook  | In progress |
| Toast | @wibblymat   | http://codepen.io/wibblymat/pen/avAjq |
| Layout (site) | @addyosmani  | https://github.com/google/web-starter-kit/issues/295 |
| Layout (app) | @addyosmani  | unassigned | [Look](http://www.polymer-project.org/components/paper-elements/demo.html)
**Technical details:**

* Components need to support all of the browsers listed in our matrix
* Components should be written using CSS and vanilla JS (no jQuery or additional libraries)
* If we're sticking with Sass, must be written with Sass or CSS and we'll tweak as necessary.
* Maintain fidelity with the Polymer paper elements as closely as possible.
* Attempt to style native HTML elements over wrapping where possible (to preserve accessibility)

**Web Starter Kit extras**

* [Material layout](https://github.com/google/web-starter-kit/issues/295)
* [Bring in the new Roboto](https://github.com/google/web-starter-kit/issues/294)
* [Style guide > Icons](https://github.com/google/web-starter-kit/issues/293)
* [Theming support](https://github.com/google/web-starter-kit/issues/292)
* Refresh style guide to Material Design

**Notes**

* All elements will go through a UX review from the Material Design team before getting shipped as part of Web Starter Kit to make sure we're not messing up :)
* The Polymer paper elements are going to be undergoing an accessibility review in the coming months. We'll keep a close eye on this and integrate any learnings that apply to our element set.

Inspiration:

![](http://i.imgur.com/N3uoYYD.png)

![](http://i.imgur.com/jbU9UnP.png)

I'll work with Google's MD team to try getting a review process in place for anything we create here.

**Comment by addyosmani** [comment]
The list of components the team are happy to proceed with for the 0.6.0 release have been sufficiently evolved that we'll be moving any further components to the next milestone. We're going to continue work on polish and hope to have a release out in the next month or two.

**Comment by ragingwind** [comment]
:+1:

**Comment by mkarthck** [comment]
@addyosmani When are you going to open source the material design lite code.

**Comment by addyosmani** [comment]
End of June. It'll be in a new repository of its own with a new site.

**Comment by mkarthck** [comment]
Thank you. Is the base design of elements in material-design-lite same as
the one shared in the codepen above??

Thanks
Karthik

**Comment by Garbee** [comment]
In MDL all the designs are based only on the specification itself and from discussions with the MD team for how things should be done that aren't clearly specified.

**Comment by remicastaing** [comment]
What will be the dependencies of MDL?

**Comment by Garbee** [comment]
The output is pure CSS and JS. Beyond that, I don't believe we are announcing anything in the source-editing side since we are still working out some details in that workflow.

Rest assured, MDL is launching very soon and you can get all your questions answered. Until then, we need to focus on finishing it up and not talking about things that may change.

**Comment by remicastaing** [comment]
Thanks for the answer and good luck. I will stay tuned.

**Comment by amcdnl** [comment]
@addyosmani is there a prelim repo out there for the new kit?

**Comment by mkarthck** [comment]
HI Guys,
   When are you going to release the version? It was supposed to be in the last week..

thanks
Karthik

**Comment by McOussKing** [comment]
Hello @addyosmani 
can i help in this project :+1:  ?

**Comment by addyosmani** [comment]
Help with replying to project bug reports and issues is always welcome :sparkles: 

New version: check out master. We currently have the new Material version in there, powered by http://getmdl.io We're also working on ES6 support at the moment so lots of new stuff. I'd suggest testing what's in this repo. We're aiming to get out a new release in the coming weeks once everything has been battle tested.

**Comment by McOussKing** [comment]
Thank you
i like MDL but the class are bit different that's why people choose Bootstrap because it's more clear and practical for Developers, Here a simple comparison :

http://demo.tutorialzine.com/2015/07/comparing-bootstrap-with-mdl/?grid
MDL is better in result but Bootstrap source code is more clear
