### ISSUE TITLE
Document back-end and deployment

### ISSUE THREAD

**Issue by wernight** [google/web-starter-kit#315]
It's really nice for client side but there is no documentation on how it might integrate with a server side script.

It could show a few examples using one or more of the prominent web frameworks like Node.js or Django (also supported on Google Cloud).

One of the biggest challenge is that the included build system need to be integrated with the templating system of existing frameworks. On this point Bootstrap/Foundation are straightforward as they have no build process.

**Comment by nicolasgarnier** [comment]
Seems like backends and deployment docs/configs is now taken care of in https://github.com/google/web-starter-kit-extras. See #330 

Closing this. Let me know if I missed anything.
