### ISSUE TITLE
Create templates to match Web Fundamentals Responsive Design Patterns

### ISSUE THREAD

**Issue by petele** [google/web-starter-kit#338]
in addition to the standard index.html and basic.html templates, add templates for:

* [Mostly fluid](https://developers.google.com/web/fundamentals/layouts/rwd-patterns/mostly-fluid.html)
* [Column drop](https://developers.google.com/web/fundamentals/layouts/rwd-patterns/column-drop.html)
* [Layout shifter](https://developers.google.com/web/fundamentals/layouts/rwd-patterns/layout-shifter.html)
* [Off canvas](https://developers.google.com/web/fundamentals/layouts/rwd-patterns/off-canvas.html)

Once done - please file an issue with Web Fundamentals and we'll update the documentation there to use the same code/samples as you've used.

**Comment by addyosmani** [comment]
@devnook if I'm correct, you ended up implementing these. It would be interesting to review them again and see how easily they can be transitioned to Material Design for the newer layouts.

**Comment by addyosmani** [comment]
We've decided to implement responsive layout templates for the new set of components in material design lite. These will try to tackle the above use-cases but we'll probably ship with 2-3 to begin with and iterate. Let's file an upstream issue to keep track.
