### ISSUE TITLE
scripts not copied to /dist/ when running gulp (gulp default)

### ISSUE THREAD

**Issue by lbordas** [google/web-starter-kit#420]
Hi.

It seems new scripts I create under /app/scripts/ folder don't get copied to /dist/scripts/ when running gulp (gulp default).

Thanks.

**Comment by Betrin13** [comment]
https://github.com/yeoman/generator-webapp/issues/512
Use this command to install gulp-if to version 2.0.0
npm install --save gulp-if@2.0.0

Worked for me
