### ISSUE TITLE
Support Templating / Other Architectures Other than Static HTML

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#425]
Issue raised by @tommyskalberg on Web Fundamentals: https://github.com/google/WebFundamentals/issues/711

This could be addressed by a documentation / recipe.

To make it easier to do, remove the dependency between HTML and JS.

**Comment by addyosmani** [comment]
Folding this issue into https://github.com/google/web-starter-kit/issues/425. I think it would be nice to have a recipe about this.
