### ISSUE TITLE
Static asset revisioning?

### ISSUE THREAD

**Issue by liuwenchao** [google/web-starter-kit#437]
Asset revision has become a necessary building feature and good practice in web apps, what do you think of adding [gulp-rev](https://github.com/sindresorhus/gulp-rev) in gulpfile.js?

**Comment by addyosmani** [comment]
Just talked to @gauntface about this again. We agree that baking in static asset re-visioning by default tends to cause more issues than it's worth. As we're trying to tackle a good baseline for beginners and intermediate devs, this feature request isn't a great fit for us.

We do appreciate the suggestion however :)

**Comment by liuwenchao** [comment]
https://github.com/smysnk/gulp-rev-all saved my day :+1:
