### ISSUE TITLE
Our tags for lists (ol, ul) are forced to the left

### ISSUE THREAD

**Issue by greenido** [google/web-starter-kit#486]
It might be good to have a global option for developers who wish to use WSK to RTL languages.
Currently, our sass force the list element to be on the 'left' side so even if the developer is changing the 'body' to 'direction:rtl' or dir:rtl it wont' help. 
Please see an example below:
![screenshot 2014-10-19 18 16 31](https://cloud.githubusercontent.com/assets/61472/4693596/e418e70e-57a2-11e4-8ee3-a511ffd34ca9.png)

**Comment by addyosmani** [comment]
@sindresorhus has mentioned in the past that solving RTL via tooling might be the right way to scale this long term. Perhaps we could add a note to the docs about how to use https://github.com/MohammadYounes/rtlcss with the WSK styles?

**Comment by addyosmani** [comment]
We're going to solve RTL as part of a new internationalisation and localisation plan for Material Design Lite.

**Comment by greenido** [comment]
OK - Sounds good.
Any ETA?
