### ISSUE TITLE
Material-Sprint: app/styleguide/animation

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#498]
### demo.html

* Much whitespace when not needed eg https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/animation/demo.html#L9 this can be tidied up

* JavaScript logic in HTML. Move to JS file. https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/animation/demo.html#L25

* JS only deals with "on load" of document. What if an element is added programatically later.

**Comment by addyosmani** [comment]
Should be addressed by https://github.com/google/web-starter-kit/commits/material-sprint?author=jasonmayes (December patterns sprint by Jason)
