### ISSUE TITLE
Material-Sprint: app/styleguide/button

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#499]
### demo.html

* Much whitespace when not needed eg https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/button/demo.html#L9 this can be tidied up

### button.js

* For readability lets use more meaningful variable names. For example on line 3 constructor we have el, we should call this element to be clearer. Same in other parts of file eg line 26 and 90 etc..

* Move functions to prototype (lines 22 - 87) https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/button/button.js#L22 After discussing this with Addy, conclusion is that it was better to favor memory savings.  This means private variable declarations that need to be used in a prototyped function would need to be converted from var x to be this.x  so it can be accessed. We should therefore use the common convention of adding an underscore on the end to indicate it is private and shouldnt be used directly. So the variable would be defined as: this.x_ = blah;

* Initialize declared variables with a default. Eg https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/button/button.js#L8 same elsewhere. Will allow you to loose part of a conditional later on - easier to read. Eg if scale and size were initialized on lines 42 and 43, the conditional directly proceeding would not need the else statement and only overwrites if start is true. Line 53 is then also redundant as it could have been initialized above in one line. Etc...

* Remove unneeded whitespace where it makes sense eg on line 15 https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/button/button.js#L15

* To make this IE9 friendly use an alternative to classlist.add and classlist.remove on 73 and 76. We should really try and get IE9 support if possible.

* What happens when paper buttons are added to the dom via javascript AFTER the document load has already fired? Handle this case as it is quite possible someone will need to programatically add a button.

* Put all classes and constants in their own respective private enum objects near top of file so they can easily be changed in 1 place going forwards. For example:

```JAVASCRIPT
this.ClassNames_ = {
  TRANSITION_LONG: 'transitionLong',
  UNSCALED: 'unscaled',
  SCALED: 'scaled'
};
```

**Comment by addyosmani** [comment]
Should be addressed by https://github.com/google/web-starter-kit/commits/material-sprint?author=jasonmayes (December patterns sprint by Jason)
