### ISSUE TITLE
Material-Sprint: app/styleguide/card

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#500]
### demo.html

* Use semantic HTML. For example for "Card-heading" we have spans, but if it is a heading it makes sense to use a h2 or such. Same elsewhere.

* Much whitespace when not needed eg https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/card/demo.html#L9 this can be tidied up

* html lang attribute is not populated with anything.

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.
