### ISSUE TITLE
Material-Sprint: app/styleguide/checkbox

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#504]
### demo.html

* Much whitespace - not needed eg https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/card/demo.html#L9 this can be tidied up

### checkbox.js

* Move functions to prototype. After discussing this with Addy, conclusion is that it was better to favor memory savings. This means private variable declarations that need to be used in a "prototyped" function would need to be converted from var x to be this.x so it can be accessed. We should therefore use the common convention of adding an underscore on the end to indicate it is private and shouldnt be used directly. So the variable would be defined as: this.x_ = blah; Same applies to function names that should be private.

* More meaningful names for varables eg https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/checkbox/checkbox.js#L4 "l" should be "label" for readability.

* For classname strings lets use camelCase everywhere for consistency? Currently some have dashes mixed with camel case. Either keep all lowercase-with-dash, or all camelCase.

* Remove console.log statements. Can break IE when console is not open!

* Put all classes and constants in their own respective private enum objects near top of file so they can easily be changed in 1 place going forwards. For example:

```JAVASCRIPT
this.ClassNames_ = {
  TRANSITION_LONG: 'transitionLong',
  UNSCALED: 'unscaled',
  SCALED: 'scaled'
};
```

* Remove use of classlist to allow support for IE9. See my original submission for checkboxes which works in IE9. https://github.com/google/web-starter-kit/blob/gh-pages/material/lite/checkboxes.js

**Comment by addyosmani** [comment]
Should be addressed by https://github.com/google/web-starter-kit/commits/material-sprint?author=jasonmayes (December patterns sprint by Jason)
