### ISSUE TITLE
Material-Sprint: general feedback

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#505]
* Would be wise to prefix all classes that are required in HTML to be prefixed with "wsk" eg "wskCheckbox" to minimize clashing with 3rd party styles / class names

* Element classnames are not consistent in their naming method. Some have dashes some are a form of camel case. I believe style guides prefer regular camel case eg "myClassName" - need to standardize on one form across all components.

* All demo.html HTML files - general whitespace tidy up required. For example see https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/fab/demo.html#L9

* Generally speaking many components need to consider situation where by instances of that component are made after the document load. Eg programatically using JavaScript. 

* It would be nice to have consistency between implementations. I am happy to write an interface or such which all "components" should implement for the JS layers. This would contain common methods we can be sure are available for key life events (eg when you need to programatically add a new instance after dom load), and also define a skeleton for where to position things eg enums, function prototypes etc so ordering between all components is familiar too. @addyosmani let me know if this is a route we should take for final production version.

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.
