### ISSUE TITLE
Material-Sprint: app/styleguide/header-panel

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#506]
### header-panel.js

* Use Strict should be limited to your function scope. Declaring it outside of this leads to issues with code that is not strict. For example consider you have strict code like this which you then append before some non strict code (3rd party site). The fact this is declared globally  means it will assume the whole site is strict, when it is not, which of course then breaks the site. :-)

* Minor nitpick but it would be more readable and use less indentation if the window load event listener was simply defined at end of file to a named function rather than an anonymous one. This also makes it easier to convert later for situations where you need to instantiate things after a window load (eg at run time).

* In fact it might be better to make this a class like other components submitted for consistency across all components. Eg see https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/button/button.js

**Comment by addyosmani** [comment]
Should be addressed by https://github.com/google/web-starter-kit/commits/material-sprint?author=jasonmayes (December patterns sprint by Jason)
