### ISSUE TITLE
Material-Sprint: app/styleguide/icons

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#508]
### demo.html

* Class attribute quotes should be double quotes not single for consistency.

* Are the divs needed? I may have missed something here, but I think you could apply style of "preview" class to the anchor tag instead?

**Comment by codeandrop** [comment]
Hi @addyosmani, according to you latest commit you have this "Please note that the icons here have been removed as they have changed once again. We will not be including them
for another few days until the newer set has landed. Please ignore for now." Should I fix the commented  code or leave as is?

**Comment by addyosmani** [comment]
We'll be shipping support for the Material Design icons font in the coming months as part of #674. Given that this work is being tackled there, closing this.
