### ISSUE TITLE
Material-Sprint: app/styleguide/navigation

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#509]
### sidenav.js

* Use Strict should be limited to function scope. Declaring outside of this leads to issues with code that is not strict. For example consider you have strict code like this which you then append before some non strict code (3rd party site). The fact this is declared globally  means it will assume the whole site is strict, when it is not, which of course then breaks the site. :-)

* Is the outer closure needed? Prevents people from instantiating new versions of the class outside of this code which may be needed if elements are created after the document load.

* Generally would be nice to have more descriptive names for variables for easier readability. For example https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/navigation/sidenav.js#L47 "cb" could be called "callback"

* "sidenavs" should be "sideNavs" to keep consistency with other camel cased variables. Same for sidenav etc...  https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/navigation/sidenav.js#L74 

* Nitpick but it would be nice to have states in an enum https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/navigation/sidenav.js#L8 eg:

``` JAVASCRIPT
this.States_ = {
  'OPEN': 0,
  'CLOSE': 1
}
```

This way they are all collated within the States_ property and easy to add more for things that are related if more states should be added at some point in future.

* Move functions to prototype. After discussing this with Addy, conclusion is that it was better to favor memory savings. This means any private variable declarations that need to be used in a prototyped function would need to be converted from var x to be this.x so it can be accessed. We should therefore use the common convention of adding an underscore on the end to indicate it is private and shouldnt be used directly. So a variable would be defined as: this.x_ = blah; For example this var would need to change: https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/navigation/sidenav.js#L11

**Comment by addyosmani** [comment]
Should be addressed by https://github.com/google/web-starter-kit/commits/material-sprint?author=jasonmayes (December patterns sprint by Jason)
