### ISSUE TITLE
Material-Sprint: app/styleguide/radio

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#510]
### button.js

* Consider putting classname strings in their own enum object near top of file so they can easily be changed in 1 place going forwards. For example:

```JAVASCRIPT
this.ClassNames_ = {
  TRANSITION_LONG: 'transitionLong',
  UNSCALED: 'unscaled',
  SCALED: 'scaled'
};
```

* Move functions to prototype. After discussing this with Addy, conclusion is that it was better to favor memory savings.  This means private variable declarations that need to be used in a prototyped function would need to be converted from var x to be this.x  so it can be accessed. We should therefore use the common convention of adding an underscore on the end to indicate it is private and shouldn't be used directly. So the variable would be defined as: this.x_ = blah;

* What happens when radio buttons are added to the dom via javascript AFTER the document load has already fired? Handle this case as it is quite possible someone will need to programatically add a button.

* Use Strict should be limited to function scope. Declaring outside of this leads to issues with code that is not strict. For example consider you have strict code like this which you then append before some non strict code (3rd party site). The fact this is declared globally  means it will assume the whole site is strict, when it is not, which of course then breaks the site. :-)

**Comment by addyosmani** [comment]
Should be addressed by https://github.com/google/web-starter-kit/commits/material-sprint?author=jasonmayes (December patterns sprint by Jason)
