### ISSUE TITLE
Material-Sprint: app/styleguide/textfield

### ISSUE THREAD

**Issue by jasonmayes** [google/web-starter-kit#512]
### textfield.js

* Remove commented out code that is no longer needed.

* Is line 46 redundant? Can just use inputs[i] in the constructor instead on the line below? https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/textfield/textfield.js#L46

* Remove console.log's for production code - I believe it can cause issues in IE if the dev tools are not open (the console object does not exist until it is open).

* Move functions to prototype. After discussing this with Addy, conclusion is that it was better to favor memory savings.  This means private variable declarations that need to be used in a prototyped function would need to be converted from var x to be this.x  so it can be accessed. We should therefore use the common convention of adding an underscore on the end to indicate it is private and shouldn't be used directly. So the variable would be defined as: this.x_ = blah;

* Use Strict should be limited to function scope. Declaring outside of this leads to issues with code that is not strict. For example consider you have strict code like this which you then append before some non strict code (3rd party site). The fact this is declared globally  means it will assume the whole site is strict, when it is not, which of course then breaks the site. :-)

**Comment by addyosmani** [comment]
Should be addressed by https://github.com/google/web-starter-kit/commits/material-sprint?author=jasonmayes (December patterns sprint by Jason)
