### ISSUE TITLE
Material-Sprint: override the default pallets

### ISSUE THREAD

**Issue by bsr203** [google/web-starter-kit#514]
Hello,

Currently, the pallet contains color def and used pallets. If they were separate, I can override first importing colors only, then define the the variables with custom values, and further include any styleguide scss.

```
_variables.scss
-----
@import "palette/colors";
/* ==========  Used Palettes  ========== */
$primaryPalette: $palettePink;
$accentPalette: $paletteGrey;
...

then

@import "variables";
@import "resets/h5bp";
@import "typography/typography";
..
@import 'navigation/sidenav-horizontal';

```

Also, all the variables need `!default;` at the end, so can be overridden.

```

/* ==========  Used Palettes  ========== */
$primaryPalette: $palettePink !default;
$accentPalette: $paletteBlueGrey !default;
$secondaryPalette: $paletteGrey !default;
..
```

please let me know if any other way to do this? thanks.

**Comment by sgomes** [comment]
I think we can close this now, right @gauntface?

**Comment by gauntface** [comment]
+1
