### ISSUE TITLE
Implement additional web layouts

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#524]
We were thinking it would  quite useful to include a few boilerplate layout examples of how to build simple, but real one pagers using some of our existing components. 

These could live in a `/layouts` or `/samples` directory, or at the top-level depending on how many we ended up shipping. If we prefer, they could be moved to a new repo, but let's start off in the material-sprint branch.

Some of the suggestions we've had are quite straight-forward whilst others involve a little more transition work. My take is that we should start off with what is simple and go from there :) Layouts ideally won't require too many of their own new assets to avoid bloating up the package.

*Open question:* Should some of the existing navigation examples that are not strictly unique also live beside these layout samples?

**Comment by abodacs** [comment]
Is there a plan to design  Dashboard Layout?

**Comment by MikeMitterer** [comment]
+1 For Dashboard Layout!

**Comment by addyosmani** [comment]
Could you share some samples of what you had in mind for a Dashboard layout?

**Comment by abodacs** [comment]
i want see how would something like https://www.google.com/settings/dashboard implement in new material design concepts
http://keen.github.io/dashboards/ popular now on github

**Comment by abodacs** [comment]
@addyosmani 
http://kyleledbetter.com/polymer-google-finance/
http://www.materialup.com/designs/233-google-trends
These are samples in mind for a Dashboard layout

**Comment by codeandrop** [comment]
@addyosmani Can we use Google Charts or D3 for charts? or this will introduce overhead to WSK? I can start off with a registration or a dashboard sample, (maybe I can create a samples directory, since there is a layout directory to avoid confusion).

Let me know.

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.

**Comment by codeandrop** [comment]
ok @addyosmani let me know if there is something I can help with.
