### ISSUE TITLE
Implement Tabs component

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#535]
![screen shot 2014-11-11 at 15 26 29](https://cloud.githubusercontent.com/assets/110953/4995210/2143c9a2-69b7-11e4-9db0-ff4154f8e4b7.png)

* Tabs are presented as a single row.
* Tabs should not be nested. Content in a tab should not consist of another set of tabbed content.
* A set of tabs contains at minimum a pair of tabs and no more than six tabs.
* Tabs control the display of content in a consistent location.
* The tab corresponding to the visible content is highlighted.
* Tabs are grouped together and the group of tabs is in turn connected with their content.

Polymer: http://www.polymer-project.org/components/paper-tabs/demo.html
Angular: https://material.angularjs.org/#/demo/material.components.tabs
CSS: http://codepen.io/keremciu/details/EgGcu/

More visuals:

![](http://material-design.storage.googleapis.com/publish/v_1/quantumexternal/0Bx4BSt6jniD7SWtvczhLbU11Uzg/components_tabs_usage_mobile1.png)

**Comment by addyosmani** [comment]
@sgomes It would be great if we could re-explore this in the new year. I think I remember throwing some prototypes over the fence but I could be wrong :)

**Comment by sgomes** [comment]
@addyosmani Yup, will be working on this this week.

**Comment by addyosmani** [comment]
:+1:

**Comment by sgomes** [comment]
Update, we have content tabs, after https://github.com/google/web-starter-kit/commit/67f9fb4bec65b0e3d5d83848d9d278dc15f56130.

Full tabs as per the Material Design spec are in progress, and will be part of `wsk-layout`. Will update once they're in.

**Comment by sgomes** [comment]
Done! Full spec implemented in https://github.com/google/web-starter-kit/commit/487170c011df05e50d6c5753b20f72550198c07d
