### ISSUE TITLE
gulp serve:dist  not updating images as expected

### ISSUE THREAD

**Issue by stevegw** [google/web-starter-kit#542]
chnaged to
When using gulp serve:dist the image files where random somethimes it worked sometime not

Investigated and tried the following its now working better ... I'm not a gulp expect. just started exploring the starter kit.

var newer = require('gulp-newer');
var imagemin = require('gulp-imagemin');
.
.
.

// Minify any new images
gulp.task('images', function() {

  // Add the newer pipe to pass through newer images only
  return gulp.src('app/images/**/*')
      .pipe(newer('dist/images'))
      .pipe(imagemin())
      .pipe(gulp.dest('dist/images'));

});

**Comment by addyosmani** [comment]
Closing due to lack of information. We're happy to reopen if you can supply more details on what went wrong.
