### ISSUE TITLE
Mobile Highlights Module Z-Index

### ISSUE THREAD

**Issue by lliamscholtz** [google/web-starter-kit#543]
![screen shot 2014-11-17 at 4 19 55 pm](https://cloud.githubusercontent.com/assets/1786921/5071015/9f87154a-6e75-11e4-8a25-7611b0e4fb4f.png)

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.

On this specific issue: please consider the material-sprint branch stale.
