### ISSUE TITLE
Escape the collapsed menu (ESC / Click on body)

### ISSUE THREAD

**Issue by Maikeximu** [google/web-starter-kit#545]
I can close the collapsed menu by clicking the right part of my page (would like to see someone push the ESC to the repo) but main problem is you are stuck clicking the hamburger icon if you scroll to a module-highlight section (any click will not work when you are at this section).

I guess the problem is inherent of the full-width properties of the module-highlight.

![It works by clicking anywhere on the left part of the page](https://cloud.githubusercontent.com/assets/4722100/5107180/c4a68b7c-6fff-11e4-87b0-f0a60a7fa5bf.png)

* It works by clicking anywhere on the left part of the page because it's plain text.

![Doesn't work because of the module-container](https://cloud.githubusercontent.com/assets/4722100/5107190/df28638a-6fff-11e4-9ed1-c922ed8f8684.png)

* It doesn't work because of the highlight-module

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.
