### ISSUE TITLE
Questions / Thoughts

### ISSUE THREAD

**Issue by xocialize** [google/web-starter-kit#574]
First off let me start by saying this is a great effort and I'm very happy to see this project in motion.  I do have a couple of questions about the implementation as it is.  

This is my first foray into the gulp / sass implementation so if I'm way off base then my apologies as this could be my ignorance more than any real issues.  The below items are referring to the material-sprint which I do know is still pre-release and very subject to changes.

My first question is about SASS and how the imports have been used for the demos.  I've noticed that the files have a way of requesting the same imports which works great for the demos but I believe when I'm trying to setup up a global implementation of WSK using the main.scss file that I'm getting a lot of re-import of the exact same stylesheets as each demo put's its dependencies in the _file and not the demos.scss.    So would it be better to use a comment about the dependencies in the _file and then do the import in the demos.scss file?

My next question is about the javascripts and dynamic content.  Right now I'm testing an implementation that uses hogan.js for templates and when I call in a section of HTML then in some instances I'm not seeing the elements of that template being properly initialized.  I can work around that by essentially running the window.load stuff that's happening but that is adding a fair amount of additional code.  What are your thoughts for moving that code out into something like a module init function and then using the window.load to call the module init function?  I'm not sure if it would make sense to use some type of scoping for the init as well as dynamic content tends to end up in a child element for my type of scenario.

My last item is more of just an opinionated thought about the default coloring in the style guide.  Most sites today tend to use the off color for the background and the pure white for content and sidebars.  For a good example we can refer to http://www.google.com/design/spec/material-design/introduction.html.  If no one has any strong objections I would suggest swapping the sidebar and background colors in the style guide as well as make the preview blocks white as well.

**Comment by abodacs** [comment]
Is there a datepicker implementation @addyosmani  ??

**Comment by nicolasgarnier** [comment]
Hey @xocialize, Web Starter Kit ha changed a lot in the past 8 month including switching to Material Design Lite for the Style/components. I'm closing this because it's been sitting here for a while but please let me know if you still have qustions.

@abodacs See: https://github.com/google/material-design-lite/issues/782
