### ISSUE TITLE
Table & Print taking too much space

### ISSUE THREAD

**Issue by Maikeximu** [google/web-starter-kit#578]
I was wondering how to manage the CSS print style in order to print the tables without a line break after every td which is weird.

![capture d ecran 2014-12-20 a 10 44 18](https://cloud.githubusercontent.com/assets/4722100/5514430/2fee4eb8-8835-11e4-90e7-a1fe2f9b0699.png)

**Comment by addyosmani** [comment]
In WSK 0.6.0, the current tables styles are going away and we're returning to a leaner set of styles for them. This specific issue is no longer going to be an issue, but we'll double check everything is print friendly for the next release.
