### ISSUE TITLE
dist/material-styleguide.html doesn't load correctly [material-sprint]

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/web-starter-kit#580]
In the material-sprint branch, the statically-built version of `material-styleguide.html` (i.e. the version in `dist/material-styleguide.html` created by `gulp`) usually doesn't load correctly from localhost--the main content frame appears to be blank.

To reproduce:

````sh
$ git checkout material-sprint
$ gulp
$ cd dist
$ python -m SimpleHTTPServer
$ open http://localhost:8000/material-styleguide.html # no content in main frame >50% of the time
````

This seems to happen if the browser is able to load the styleguide-demo iframes before sizeDemo() is [able to attach the onload handlers](https://github.com/google/web-starter-kit/blob/material-sprint/app/material-styleguide.html#L174), and so some are never called, which means the `demosLoaded` class is never added to `<body>`. (Which is more likely to happen if loading from localhost, without browser-sync being involved.)

**Comment by addyosmani** [comment]
I've been able to reproduce this locally. We're currently rewriting the material-styleguide.html implementation to move away from iframes as much as possible. This work hasn't yet been checked in to the material-sprint branch, but soon you will just have a static HTML file with all of the markup existing in the same file so this issue will disappear.

cc @gauntface as an FYI that this is currently occurring.
