### ISSUE TITLE
New-year issue triage

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#585]
- [x] Go through all issues
- [x] Close code and style improvements we've landed in the last sprint
- [x] Move non P1 items out of the current 0.6.x sprint
- [ ] Author README messaging in prep for 0.6.x (e.g please only report tooling issues for now)
- [ ] Resolve what we're doing about material.css/material.js
- [ ] Create issues to flesh out the documentation plan for 0.6.0 
- [ ] Improve issue and contribution submission guidelines

**Comment by arthurvr** [comment]
You've been doing nice work going over all issues, @addyosmani! :trophy:

**Comment by addyosmani** [comment]
Thanks @arthurvr!

**Comment by codeandrop** [comment]
If you need an extra hand on any issue just let me know, I'll be happy to help!

**Comment by addyosmani** [comment]
Thanks @codeandrop! Any help with bug triage / helping us close tickets would be hugely appreciated. We're still at about ~44 open atm :) Some of these are to help us track work on the next major version (0.6.0 - in the material-sprint branch) but others are less relevant now.

**Comment by codeandrop** [comment]
Sure @addyosmani I will start reviewing issues labeled P1 and continue the conversation there, I'll get back on this one if needed.
