### ISSUE TITLE
Explore reducing duplication in layout

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#587]
At the moment the default layout in the material-sprint branch has a wsk-layout where the header and drawer contents are identical and presumably duplicated to make the CSS simpler.

This is frustrating to use as you have to maintain the same thing in multiple places and I would have thought this would be weird in terms of understanding the markup.

**Comment by addyosmani** [comment]
I totally appreciate that you would want to keep duplication to a minimum. That said, I remember there being technical and visual layout reasons why we needed to do this the way we did. 

cc @sgomes who might be able to expand.

**Comment by sgomes** [comment]
The issue is that you may want to have more control. Some layouts have items in the header that they don't want in the sidebar, such as search boxes.

We could add some complicated classes to only show in one or the other, but ultimately, it's easier to just give the user full control.

**Comment by gauntface** [comment]
Fair enough - closing the bug.
