### ISSUE TITLE
.sass-cache and .gitignore

### ISSUE THREAD

**Issue by joaostein** [google/web-starter-kit#590]
I recently pulled the project and noticed that I had a .sass-cache file.  I did a quick research and found out that this was removed here bae66fecd972aa2fcd4cc397d3aeca8d579e60bf.  I assume it expects us to add it to the global .gitignore config, is this correct?

If so, would't it be interesting to add some information about this on the wiki section or any other place? Maybe pointing out some information for people that are not aware of global .gitignore and some instructions on how to do so?

**Comment by antleblanc** [comment]
@joaostein Since the switch from LibSass, the `.sass-cache` folder is no longer generate.

**Comment by joaostein** [comment]
@antleblanc got it! Just to make sure -- I basically had this legacy folder from before LibSass. When I pulled from upstream it merged a new version of `.gitignore` with the old `.sass-cache` folder, creating this issue, is it correct? For now can I just remove the `.sass-cache` and I'm good to go?

**Comment by antleblanc** [comment]
@joaostein For sure! You can now delete the `.sass-cache` folder and you're good to go.

**Comment by joaostein** [comment]
@antleblanc thank you so much :)
