### ISSUE TITLE
Should include at docs

### ISSUE THREAD

**Issue by gilpanal** [google/web-starter-kit#591]
I think it's necessary to include this command at installation, or something similar:

$ sudo gem install sass

So when people run "gulp serve" styles are available.

I think it's not clear at the documentation, at least for me.

Thanks!

**Comment by antleblanc** [comment]
@gilpanal A new version is upcoming (v0.6.0), you can look at the [milestones](https://github.com/google/web-starter-kit/milestones).

The master branch remove the dependence from Ruby.
You can review those merges #484 and #517.

**Comment by gilpanal** [comment]
Great! Thanks for your help! I love this project!
