### ISSUE TITLE
BrowserSync.reload call in `jshint` command always returns `0 file changed`

### ISSUE THREAD

**Issue by rdmurphy** [google/web-starter-kit#593]
Hello!

[This line](https://github.com/google/web-starter-kit/blob/master/gulpfile.js#L46) in the `gulpfile.js` appears to be trying to pass along to BrowserSync the number and names of the files being linted, but it always returns `0 file changed ()`.

![screen shot 2015-01-11 at 11 09 55 am](https://cloud.githubusercontent.com/assets/419145/5696015/710bc372-9982-11e4-8429-8f7c6e16d811.png)

I actually came across this with a version of the starter kit I customized to add a `scripts` call for concatenation + uglifying and it does the same thing there. And then I noticed it was happening twice, so I kept going up the chain and found this.

Totally possible this is on the BrowserSync side of things – not really knowledgeable enough about it to hack around on it to figure it out – but currently that is not providing any useful logged information. Could be an order of operations thing?

Hope that helps!

**Comment by stevemao** [comment]
Looks like this issue is solved.

**Comment by rdmurphy** [comment]
Thanks! :+1:

**Comment by addyosmani** [comment]
Closing as fixed.
