### ISSUE TITLE
Css not being rendered/ Npm Problems/ Gulp serve not working/Cant get started developing.

### ISSUE THREAD

**Issue by Uriahs9** [google/web-starter-kit#601]
I noticed that in the style location for the index.html it had "main.css"...so the page was not being rendered because there is no main.css so in the code i changed it to "main.scss" and it showed up fine... but i noticed that there is alot of inconsistences...

the "style guide" points to "styles/components.css" this path is incomplete... i changed it to "styles/components/components.scss" but still...there are no styles on the style guide page...

What am i missing here?

**Comment by kevva** [comment]
You need to build it first. https://github.com/google/web-starter-kit/blob/master/docs/commands.md.

**Comment by Uriahs9** [comment]
Thanks for the quick reply... i saw the install.md but i just jumped in and started editing code :3 question... so after i have finished my project and i use gulp to "build" the project...how do i go about uploading it to a host? are there any special steps? will that built project be "upload ready" ?

Thanks.

**Comment by kevva** [comment]
Yup, just upload what's in the `dist` directory.

**Comment by Uriahs9** [comment]
Ok i will try it out and return to report here within the coming hours. Please do not close this thread as yet.

**Comment by Uriahs9** [comment]
Hit my toe on the wall...can't continue because of sass... i have installed both Scout and Mixture but terminal doesn't give sass version...
![sass](https://cloud.githubusercontent.com/assets/10324144/5830545/5caf2d88-a0f8-11e4-8467-5105c4874b0a.PNG)

**Comment by Uriahs9** [comment]
Ok fixed this by going to a lower version of the ruby installer...apparently the lastest versions of the installer does not have all the gem packages...

But, just when i thought i was done i ran into a problem with 'npm install' 
![npm](https://cloud.githubusercontent.com/assets/10324144/5831017/ecbb1bba-a0ff-11e4-9f0e-b351c14da77e.PNG)


I have uploaded the log to google drive if anyone can help crack down what its saying: https://drive.google.com/file/d/0B2JHimBsITS6NTNTcUxOQTVhZW8/view?usp=sharing

**Comment by Uriahs9** [comment]
Ok i took some time and i went over the instructions for this boilplate. For 1 i was using the install.md for instructions when i should have been using: https://developers.google.com/web/fundamentals/getting-started/web-starter-kit/setting-up#install-these-one-time-dependencies


but i have installed everything needed but still having problems... why are there no videos for these things? iv never had so much trouble "getting started"! 

I navigated to the folder of the webstarter kit (i renamed it to "web") and run npm install in that directory...it was going fine until this:

![npm error](https://cloud.githubusercontent.com/assets/10324144/5831348/810059aa-a107-11e4-8525-bc57d21e0cb6.PNG)

i proceeded and ran npm install gulp -g ...it seem to have installed but when i type "gulp serve" it sends back this: 
![gulp](https://cloud.githubusercontent.com/assets/10324144/5831368/d6b2b550-a107-11e4-82a5-7b17cde23ee3.PNG)

I am totally lost at the moment... all i wanted was a boilerplate with responsiveness but this is proving to be a totally different challenge...

**Comment by brucebentley** [comment]
Try deleting the node_modules folder completely, and then run `npm install` again. It looks like not all of the project dependencies have been installed properly.

**Comment by Uriahs9** [comment]
Where exactly do i delete it from? I have a node_modules folder in the following places:

C:\Program Files\nodejs\node_modules
C:\Program Files\nodejs\node_modules\npm\node_modules

I also have one in the folder with the starter kit (which i renamed web for convenience):

C:\Users\Uriahs\Desktop\web\node_modules

Forgive me for being a total novice in npm and node.js

**Comment by brucebentley** [comment]
From the project folder on your desktop. Delete node_modules from `\web`

**Comment by Uriahs9** [comment]
Ok i examined the cmd properly and the error code says that it basically needs at least nmp 2.1.5 to work where as i have v 1.4.28... so i went about and installed v 2.2.0 of npm.

I went through the instructions of upgrading NPM on windows... but i run into a problem

Link to article: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**NOTE** I used option 1, then i copied the npmrc into the C:\Users\uriahs\AppData\Roaming\npm\node_modules\npm path as instructed... but im not sure if i have the environment variables set up correctly because when i type npm -v cmd tells me "node" is not a recognized command...

I think i have my environment variable all messed up...please advise. Please also help with the correct syntax for adding the environment varible.

THANK YOU

**Comment by Uriahs9** [comment]
Update... i deleted the variables i made (made one in user variables and another in system variables) and now im getting this: 
![npm not recognized](https://cloud.githubusercontent.com/assets/10324144/5837176/2c4a28fe-a153-11e4-8d60-6a32ea90b806.PNG)


Ill say it again this is the most difficult "getting started" i have ever seen...takes so much just to get a boilerplate..

**Comment by brucebentley** [comment]
For starters, you will need to have a reference to npm in your PATH (for me on Windows 8.1, I have it listed in my User Variables, as well as System Variables b/c I'm on a corporate domain).
>
Add this line to your User Variables:
* `C:\Users\{YOUR USERNAME}\AppData\Roaming\npm;`
>
I also have these added to my System Variables:
* `C:\Program Files\NodeJS\;` _(or wherever you specified the NodeJS installation)_

Once you've added those to your PATH, close out of any Bash/Command Prompt windows you have open. Reopen them and type in `node -v` followed by `npm -v` and you should see an output of each's current version number.

After you've done that, run `npm update -g` to globally update all of your packages to the most current version. If you experience any errors in those updates, you may need to clean your cache to allow Node.JS to be upgraded to the latest version(s). _(See [David Walsh's blog post](http://davidwalsh.name/upgrade-nodejs) for more information about this...)_

> **Make sure you "Run As Administrator" when you open up a new Command Prompt for anything that will need to be globally installed.**
* `npm cache clean`
* ` npm update -g`

See if this helps you out. I totally understand your frustrations, getting NodeJS up & running on my work supplied Windows desktop was a little more tricky than getting it up and running on my personal MacBook (thanks to Homebrew).

---

Here's a coupe of links that definitely helped me get started, although alot of the information is repetitive, you can kinda/sorta mix & match to get you up and running:

1. [Installing Node.js on Windows - _Six Revisions_](http://sixrevisions.com/web-development/installing-node-windows/)
2. [Getting started in developing Node.js in Windows - _ALTIFY:SOFTWARE_](http://www.altifysoftware.com/developing-node-js-in-windows/)
3. [Installing node.js on Windows - _Vikram Kumar_](http://kumarvikram.com/installing-node-js-windows/)
4. [Installing Node.js on Windows 8 - _Gareth JM Saunders_](http://blog.garethjmsaunders.co.uk/2013/10/24/installing-node-js-on-windows-8/)
5. [Node.js On Windows 8.1 - _Tyler Butler_](http://www.tylerbutler.com/2014/08/node-js-on-windows-8-1/)

Also, I would recomment using a different command prompt ([Console2](http://sourceforge.net/projects/console/) or [ConsoleZ](https://github.com/cbucher/console/wiki/Downloads) more specifically) on Windows. These will allow you to specify additional parameters & make things **A TON** easier, especially starting out.

**Comment by sindresorhus** [comment]
I would recommend http://bliker.github.io/cmder/

**Comment by brucebentley** [comment]
Thanks @sindresorhus I completely forgot to add that! I literally just installed this a couple days ago too...

**Comment by Uriahs9** [comment]
Why did he close the thread if i haven't confirmed the problem rectified :3 I haven't tried out what you posted i was thinking of completely uninstalling node.js using revouninstaller and starting from the top using what you posted...

**Comment by brucebentley** [comment]
Did you have any luck?

**Comment by Uriahs9** [comment]
I am currently at work right now. So i can't try out everything till i get home but i have always been having issues with this new world of npm and node.js... i couldn't get started with steroids (appgyver) because of it and now i cant get started with web starter kit because of this also....


I will uninstall node.js when i go home and manually delete any left overs (npm incase it doesnt take it with it...since i used node.js to install npm)... 

I will give you guys an update in the couple hours but i dont think the thread should have been closed because it relates to web-starter-kit and i haven't even been able to get to that step because google assumes you have everything set up right already. Thanks for your continued help @brucebentley I work in IT and currently my cmd cant ping...ipconfig...etc no idea why...

My final work envionment will be on MAC so i will still have to do these on my mac once i get it (hope its easier) but i will also be programming in VS on windows which is why i need to get this sorted don't want to get left behind.

**Comment by brucebentley** [comment]
@Uriahs9 In regards to your CMD not being able to issue ping or ipconfig statements, it sounds like you might have removed something essential from your User Variables PATH or System Variables PATH.

Make sure you still have these in there (for the System Variables):
* `C:\WINDOWS\system32;`
* `C:\WINDOWS;`
* `C:\WINDOWS\System32\Wbem;`
* `C:\WINDOWS\System32\WindowsPowerShell\v1.0\;`

**Comment by Uriahs9** [comment]
@brucebentley i have reinstalled everything and have ruby, sass, npm, node at their latest stable version... i have created a new thread so others could contribute since the mod closed this one prematurely. It would be better if more people could help.

https://github.com/google/web-starter-kit/issues/604
