### ISSUE TITLE
New structure on main.scss and a new custom.scss file

### ISSUE THREAD

**Issue by codeandrop** [google/web-starter-kit#603]
Hi Guys,
Kudos on this great project! I've using the WSK for a while and I would like to propose an improvement on the main.scss file.

I propose to split main.scss in 2 files:

1. app.scss - this file will contain all the code below @import 'components/components'; which is CSS specific to the boilerplate itself.

2. custom.scss - this file will be empty but it will be a starting point to start coding since we all need to add custom CSS classes eventually.

Finally we import these 2 files into main.scss giving it some kind of purpose for managing imports and not writing CSS code here.

I can make the changes myself and create a pull request but I would like to know if this idea is good enough to make it to the master branch.

Any feedback is appreciated.

Thanks!
Andres

**Comment by fsquaredmedia** [comment]
Actually you should be breaking up your modules, layouts and base CSS files separately. This will keep you CSS manageable. All SASS files get combined and minified into one optimized file. Import only SASS files. Here is a sample of my main.scss file. Here is an excellent resource for managing CSS https://smacss.com/ 

//Base
@import '_open_sans';
@import '_variables';
@import '_base';

// Layouts
@import 'modules/_footer';
@import 'modules/_header';
@import 'modules/_wrap';

// Modules Imports
@import 'modules/_buttons';
@import 'modules/_showcase';
@import 'modules/_inputs';
@import 'modules/_backgrounds';
@import 'modules/_states';
@import 'modules/_price_box';
@import 'modules/_feature_box';
@import 'modules/_app_modal';

// Styleguide
@import 'styleguide/_header';
@import 'styleguide/_l_styleguide';

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.

**Comment by codeandrop** [comment]
Ok looking forward to see the library! You guys rock coding!
