### ISSUE TITLE
Can't Get Through Gulp Step to use web starter kit.

### ISSUE THREAD

**Issue by Uriahs9** [google/web-starter-kit#604]
<b>What you need to know:</b>

I have Node, NPM, Ruby, SASS all installed and at lastest stable realeases. (ruby isn't at it's lastest stable but the lastest stable does not have the sass gem):

![versions](https://cloud.githubusercontent.com/assets/10324144/5850254/43fdf88e-a1c8-11e4-8c9f-67560774901b.PNG)

I updated npm by using the command line and following the guide here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows **I USED OPTION 3**

I then went back to : https://developers.google.com/web/fundamentals/getting-started/web-starter-kit/setting-up#install-these-one-time-dependencies 

I scrolled down and followed the steps to "Set Up Your Web Starter Kit Project" keep in mind that i renamed the folder from "web-starter-kit" to "google web" in this case for convenience 

So i navigated to the starter kit folder using cmd (with admin rights) and typed <code>npm install</code> here are the results:

![npm install](https://cloud.githubusercontent.com/assets/10324144/5850273/abee7504-a1c8-11e4-9e9d-227b517ea4b0.PNG)

<b> I still decided to go ahead and still tried to install gulp using <code>npm install gulp -g</code> within the starter kit folder</b> heres the results:

![gulp error](https://cloud.githubusercontent.com/assets/10324144/5850310/637bad9a-a1c9-11e4-974f-b91df7e70fcf.PNG)

Who ever helps me rectify this will receive my praise forever...I really want to be using this starter kit to start my projects. Moderators please do not close this thread without issues being fixed. There is clearly something amiss here.

**Comment by brucebentley** [comment]
Just for the sake of trying, run `npm install` again without removing the node_modules folder

**Comment by sindresorhus** [comment]
@Uriahs9 It was closed (#601) because it's not an issue with WSK, but with your system and/or possibly gulp. You can still continue the discussion with the issue being closed, but keep in mind that support questions are better asked and answered on StackOverflow ;)
