### ISSUE TITLE
Why requestAnimFrame? (Material Branch)

### ISSUE THREAD

**Issue by PaulKinlan** [google/web-starter-kit#605]
I know we are using the polyfill, but what is the reason for not using the proper requestAnimationFrame name? 

It is forcing me to include the requestAnim polyfill (specifically because I am including ripple.js) and it is not clear that there is this mandatory a dependency (in my project it is unneeded)

**Comment by addyosmani** [comment]
I'm moving this to the material-design-lite repo and cc'ing you in as WSK will be dropping inclusion of it directly for 0.6.0.
