### ISSUE TITLE
Incorporate service worker-based offline support

### ISSUE THREAD

**Issue by jeffposnick** [google/web-starter-kit#606]
As discussed with @addyosmani, @PaulKinlan and others, doing something about offline support makes sense now that service workers are more widely available.

My (biased) opinion is that WSK should add offline support via https://github.com/jeffposnick/sw-precache, which can be added to the existing `gulp` build. I'll put together a PR illustrating what that change would look like.

If folks don't feel that https://github.com/jeffposnick/sw-precache would be a good fit for WSK, then we can hash out alternative ideas in this issue thread.

**Comment by addyosmani** [comment]
This has now landed.
