### ISSUE TITLE
Use a package manager to manage _h5bp.scss?

### ISSUE THREAD

**Issue by stevemao** [google/web-starter-kit#609]
I can see _h5bp.scss is completely outdate and think it would be better to use a package manager. npm looks great for this. Any thoughts?

**Comment by stevemao** [comment]
In that case I think it would be better if we include a version number in the comment.

**Comment by sindresorhus** [comment]
@alrra

**Comment by sindresorhus** [comment]
:+1: Depends on https://github.com/h5bp/html5-boilerplate/issues/1671

**Comment by addyosmani** [comment]
I'm fine with us using npm for this. Let's wait and see where the above issue on H5BP goes.

**Comment by nicolasgarnier** [comment]
Closing as we aren't using _h5bp.scss in WSK anymore with the move to Material Design Lite.
