### ISSUE TITLE
What are the recommendations for vendor scripts?

### ISSUE THREAD

**Issue by am** [google/web-starter-kit#618]
Checking the documentation and source-code I couldn't find any hints where/how could vendor scripts be added to the starter kit.

- Is there any package manager that could be used? 
- How to build those with gulp?

Maybe it just goes out of scope but I think it's a common feature that could be built-in.

**Comment by sindresorhus** [comment]
> Is there any package manager that could be used?

Sure, npm or bower. I would recommend npm.

> How to build those with gulp?

Just add the scripts to your index.html
https://github.com/google/web-starter-kit/blob/ff33b9ab2af1005afbd704326fb484a6af502fee/app/index.html#L68

and they'll get picked up by the build-process:

https://github.com/google/web-starter-kit/blob/ff33b9ab2af1005afbd704326fb484a6af502fee/gulpfile.js#L107

**Comment by arthurvr** [comment]
Is this something we're documenting somewhere? Might be worth it to do so.

**Comment by Tux1** [comment]
I would like to install materialize and some other js or css libraries. How can I add them easily to the pipe ?
