### ISSUE TITLE
question: gulp-changed vs gulp-cache

### ISSUE THREAD

**Issue by aunz** [google/web-starter-kit#620]
I notice that gulp-changed is used for styles  
```js
.pipe($.changed('styles', {extension: '.scss'}))
```
while gulp-cache is used for images
```js
.pipe($.cache($.imagemin({progressive: true,interlaced: true})))
```
Are there particular reasons to use changed vs cache? Thanks!

**Comment by stevemao** [comment]
gulp-changed - only pass through changed files
gulp-cache - all files are passed downstream

**Comment by stevemao** [comment]
@aunz does it answer your question?

**Comment by aunz** [comment]
Yes, thanks!!
