### ISSUE TITLE
rippleContainer.addEventListener should be in if-block in icon-toggle.js

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#621]
https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/icon-toggle/icon-toggle.js

Line 153 rippleContainer.addEventListener('mouseup', this.onMouseUp_.bind(this));
should be on line 147 - just before if closes.

Also TINY_TIMEOUT is 0.001 - in my case I can't see the ripple effect. Maybe this value is to low...

**Comment by addyosmani** [comment]
cc @sgomes who worked on the ripple component.

**Comment by MikeMitterer** [comment]
Almost every JS-class using rippleContainer has it on the wrong place.
Only inside if guarantees that rippleContainer is a valid object.

**Comment by addyosmani** [comment]
Thanks for the heads up, @MikeMitterer. We'll get this fixed in the material-sprint branch shortly. Appreciate you filing bugs against that branch as you work along on your port.

**Comment by sgomes** [comment]
Fixed in d6b72823af153ff6c195e03337245da70128eb37
