### ISSUE TITLE
is-upgrade is missing in MaterialSlider i

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#622]
https://github.com/google/web-starter-kit/blob/favicons-material/app/styleguide/slider/slider.js

**Comment by sgomes** [comment]
Thanks, @MikeMitterer! While this component doesn't really need the is-upgraded class, there are some changes I need to make to it that will require it, so I'll take this on.

**Comment by sgomes** [comment]
Fixed in c0e39cdd58299a44587dd6dd6032d6aa4d15debc
