### ISSUE TITLE
two stop-functions in MaterialSpinner

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#623]
https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/spinner/spinner.js

**Comment by MikeMitterer** [comment]
Another issue with "stop" - it gets never called...

**Comment by sgomes** [comment]
@MikeMitterer Oops, one of them is supposed to be "start", thanks for pointing that out!

As for not being called anywhere, that's correct and expected. These functions are meant to be public and called by the developer if they need to stop the animation. I'll add a better comment.

**Comment by sgomes** [comment]
Fixed in 917359f28e007bb71d85354c3d7b09164b3610db
