### ISSUE TITLE
Please link to my Dart port of WSK Material branch

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#624]
https://github.com/MikeMitterer/dart-wsk-material
Thx.

**Comment by addyosmani** [comment]
Hey @MikeMitterer. Thanks for linking us up to your Dart port. It's looking sharp. 

At present, the Material Sprint branch is highly WIP and is likely to change as we continue working through reviews with the Google Material Design and UX teams.   As such, we would suggest waiting a few weeks before continuing with your port as the source is likely to undergo some churn.

It might also be interesting to coordinate with @sethladd from the Dart team as they've been similarly interested in a Dart port of WSK. Once we're in a stable position with our components, we'd be happy to start linking up to other ports.

Does that make sense?

**Comment by sethladd** [comment]
Thanks for the port! Looking forward to the signal that we can start to use it.

**Comment by addyosmani** [comment]
Let's link up to the Dart port from MDL once both projects are ready. Web Starter Kit is going to focus on minimal boilerplate and tooling from now on.
