### ISSUE TITLE
The Material Ripple Consumes Clicks

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#625]
Kinlan realised that using the ripple will consume the click event on a button.

**Comment by sgomes** [comment]
@gauntface Can't reproduce, buttons seem to be working fine for me in Chrome, IE and Firefox. Could you provide more details?

**Comment by gauntface** [comment]
@paulkinlan can you provide code that reproduces please.

**Comment by sgomes** [comment]
Closing. Feel free to reopen if it turns out this is still an issue.
