### ISSUE TITLE
gulp html task clarification

### ISSUE THREAD

**Issue by code-guru** [google/web-starter-kit#626]
In `gulpfile.js` html task we have:

``` js
    // Concatenate And Minify Styles
    // In case you are still using useref build blocks
    .pipe($.if('*.css', $.csso()))
    .pipe(assets.restore())
    .pipe($.useref())
    // Update Production Style Guide Paths
    .pipe($.replace('components/components.css', 'components/main.min.css'))
```

here are few questions:
   * In the comment above csso, it said  "in case you are still using useref build block", WSK does not use useref block for css, should we add it ourselves? It already minify css file with the orginal filename, does it mean if we want concatination we should use useref block?
   * In the comment above `$.replace`, it said "update production style guide path", and in the code it refer to `components/components.css` where we don't have any components folder neither in `dist` nor in `.tmp` folder. It also refers to `components/main.min.css` where the code never generates file with `min` suffix. Could you explain these two paths, and the reason for replace command.

It would be great if someone could kindly explain this.

**Comment by stevemao** [comment]
Already answered in #357 and #597

**Comment by code-guru** [comment]
@stevemao I wonder why you referenced to your not yet accepted PR, and saying it is already answered. 

You just offered a solution for part of my answer with a PR, and the PR is not yet accepted. Your PR can't be considered as an answer!
