### ISSUE TITLE
Old versions are listed in package.json devDependencies

### ISSUE THREAD

**Issue by loljoho** [google/web-starter-kit#629]
I updated the devDependencies to more current version numbers:

https://github.com/google/web-starter-kit/pull/628

I apologise in advance if I'm doing something wrong.

As you can see, this is the very first time I've actually stepped out and done this sort of thing--I'm quite scared TBQH :<

I understand that this change ultimately has a negligible effect but I have some obsessive-compulsive tendencies and was hoping that the gesture would be appreciated.

Sorry and cheers!

**Comment by sindresorhus** [comment]
Don't worry. Nothing bad can happen :)

As for next time, you don't need to open both an issue and PR. PRs are issues ;)
