### ISSUE TITLE
Migrate to BrowserSync ^2.0.0

### ISSUE THREAD

**Issue by shakyShane** [google/web-starter-kit#630]
The upgrade path is seamless for this project and requires no action, however before I send a PR will you be wanting the UI disabled by default, perhaps with a commented line advising people that it's there? 

Info - [http://www.wearejh.com/news/browsersync-2-0/](http://www.wearejh.com/news/browsersync-2-0/)
Option docs - [http://www.browsersync.io/docs/options](http://www.browsersync.io/docs/options)

**Comment by addyosmani** [comment]
Thanks for the head's up, @shakyShane. I've just been running through the capabilities of your baked-in UI and it's very well done.

Relevant text for the team on the UI:
 
> It comes bundled with BrowserSync! That means there’s no need for any separate installs, configuration or external apps.
It runs automatically in a browser! This creates some unique use-cases that other tools simply cannot match (such as accessing the UI via a phone or tablet, for example).
It’s cross-platform! Just as BrowserSync is, the UI opens in a browser and will work on Mac, Windows and Linux.

> The UI includes the weinre project that enables remote debugging on connected devices.

Given the UI is installed by default, do you know ~ how much larger this makes the dependency tree?

I would go ahead with a PR and we'll continue local testing. Will comment back if we have further questions.

Cheers! :)

**Comment by addyosmani** [comment]
Fyi, appears to be a small rendering issue in your docs http://www.browsersync.io/docs/gulp/ :)

**Comment by shakyShane** [comment]
@addyosmani - dependencies are always a valid concern - true. The UI is extremely light-weight though, and were it not for `weinre`, the tree for the UI would only be a single level.

![deps](http://cl.ly/image/3m311a3s2Q2j/Screen%20Shot%202015-02-10%20at%2016.26.01.png)

That being said, I am absolutely thinking about having a BrowserSync-lite for power-users who really only want the sync/live reload. This would be trivial to implement as the entire UI, whilst bundled, is actually just a BrowserSync plugin.

Interested to hear everyones opinions :)

**Comment by shakyShane** [comment]
also, good catch with the docs rendering, all fixed now :)

**Comment by sindresorhus** [comment]
I haven't tried this, but does it load the settings page by default? How are the programmatic API option and the options in the UI related?

I generally think this looks good.

> BrowserSync-lite

Many tools go with a `module-core` for the core functionality and `module` for everything. I could see the use for `browsersync-core` and `browsersync` (which depends on `browsersync-core`).

**Comment by addyosmani** [comment]
> I haven't tried this, but does it load the settings page by default? 

From my testing the UI is available, but isn't loaded to the end-user by default. They have to manually navigate to the URL for it in order to access, which feels okay to me.

**Comment by shakyShane** [comment]
Yeah I decided against forcing it to be opened by default. For anyone wondering though, the `open` option takes any availableurl, so to open the UI instead of the default:

```
browserSync({
    server: "./app",
    open: "ui" //or `ui-external`
});
```

**Comment by stevemao** [comment]
This is fixed in https://github.com/google/web-starter-kit/commit/d7b0b9b249fc6e11f3c617067e06ce6b6eb67561

**Comment by addyosmani** [comment]
Thanks for the reminder, @stevemao!

**Comment by shakyShane** [comment]
:+1:  - enjoy :)

**Comment by addyosmani** [comment]
Appreciate the updates once again, @shakyShane!
