### ISSUE TITLE
Add color to .wsk-textfield[disabled]

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#632]
If the status of the input-field switches from disabled to enabled and back agin the text in the textfield stays black without the color setting.
![issue-wsk-textfield](https://cloud.githubusercontent.com/assets/116654/6202899/900b7a5e-b504-11e4-8452-eed540dda8f5.png)

**Comment by addyosmani** [comment]
Confirmed. cc @sgomes

**Comment by addyosmani** [comment]
Closing as part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674.
