### ISSUE TITLE
Fix up JSHint Issues

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#634]
At the moment I'm getting JSHint errors for a lot of the components when I build the project:

Message:
    JSHint failed for: /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/scripts/main.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/scripts/ui-handler.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/animation/animation.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/button/button.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/column-layout/column-layout.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/checkbox/checkbox.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/icon-toggle/icon-toggle.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/item/item.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/layout/layout.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/radio/radio.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/ripple/ripple.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/slider/slider.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/spinner/spinner.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/switch/switch.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/tabs/tabs.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/textfield/textfield.js, /Users/mattgaunt/Projects/Code/simple-push-demo-backend/frontend/app/styleguide/tooltip/tooltip.js

**Comment by addyosmani** [comment]
The MDL repo should have no issues with JSHint atm. Is it possible for you to use that repo for your needs? If not, we can look at backporting those changes into here.

**Comment by gauntface** [comment]
This is a push notification demo, not worth the overhead to change at this point. 

If it's been addressed then no worries, just close this.
