### ISSUE TITLE
Proposal for wsk Dialog Material style / feature request

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#640]
Would be cool if you could add some dialog styles.
Here is my proposal: https://github.com/MikeMitterer/dart-wsk-angular/blob/master/lib/sass/wsk_dialog/_wsk_dialog.scss

This is how it looks like: http://wsk.angular.mikemitterer.at/styleguide/index.html#/dialog

**Comment by addyosmani** [comment]
Closing as part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674.
