### ISSUE TITLE
Proposal for Accordion / feature request

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#641]
Hi, would be cool if you could add an Accordion.
Here is my proposal: 
https://github.com/MikeMitterer/dart-wsk-material/tree/master/lib/sass/accordion

Script (Dart - sorry no JS)
http://goo.gl/iIsbpD (But structure is close to your other JS-samples)

Running Sample: 
http://wsk.mikemitterer.at/accordion/web/index.html

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.

Please file a feature request for this upstream on MDL if you haven't already.
