### ISSUE TITLE
Update size for RippleComponent in _downHandler

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#642]
If the component is hidden when the RippleComponent calculates its dimensions the with + height are 0 so no ripple-effect can be shown.

In my Dart-version I added a _updateDimension function in _downHandler.
I think this could be appropriate for the JS version as well 
https://github.com/MikeMitterer/dart-wsk-material/blob/master/lib/src/components/MaterialRipple.dart

**Comment by addyosmani** [comment]
Closing as part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674.
