### ISSUE TITLE
Why are comments in title case?

### ISSUE THREAD

**Issue by callumlocke** [google/web-starter-kit#643]
This is a minor thing, but the casing of comments in the gulpfile is very unconventional...

```
// Include Gulp & Tools We'll Use
// Scan Your HTML For Assets & Optimize Them
// Build Production Files, the Default Task
```

Why Are They Written Like This?

**Comment by addyosmani** [comment]
Buzzfeed case is the future! :)

In seriousness: when reading through a build-file, there are typically two types of comments we come across. Code comments explaining what a process is doing and then overall headings for these sections. We opted for title case to make it easier to catch your eye when reading through and not mixing this up with the nitty gritty details. 

That said, I'm not closed to us changing this away from title case if folks are finding it jarring at all.

**Comment by addyosmani** [comment]
@sindresorhus @passy Reading through https://github.com/google/web-starter-kit/blob/master/gulpfile.js#L105, I guess title case does look a little weird. Do you have any opinions here?

**Comment by Garbee** [comment]
Tbh, I think using just whole proper sentences is best unless it is like a section title.

> Include Gulp & Tools We'll Use
 Would seem to be best written as "Including Gulp and other tools we will use."

That being said, "title case" does look weird in other places where the writing is still clear enough. Could we simply change the title comment structure to have an extra `//` padding the line (above and below)? That would seem to be more clear to denote a section (if not just using /*) compared to title case.

**Comment by callumlocke** [comment]
I think the current wording is mostly good (clear, imperative mood sentences to introduce each task, and a small number of other comments for more detailed stuff). I just think that the title case is fussy and jarring.

I don't think there's any need (in the gulpfile at least) to artificially make certain comments more eye-catching than others. The positioning already gives the correct weight to each comment. The comments that introduce tasks, for example, are all left-aligned and form a natural pattern on the page; their importance and hierarchy reflect the code structure.

Also this is a project for people to fork and modify, so in terms of setting a style that people can continue with, simpler is better.

**Comment by sindresorhus** [comment]
Yeah, title casing is weird. Just make it a normal sentence.

**Comment by addyosmani** [comment]
Let's change it. If someone would like to take a stab at a PR happy to review. Otherwise will update early next week.

**Comment by addyosmani** [comment]
Also thanks for raising this @callumlocke :)

**Comment by callumlocke** [comment]
did no one see my PR further up? I made a couple of wording changes in addition to fixing the case. in particular the one about copying files "at the root level" is misleading

**Comment by battaglr** [comment]
I checked before doing mine. I [couldn't find yours](https://github.com/google/web-starter-kit/pulls?q=is%3Apr+author%3Acallumlocke+). :|

**Comment by callumlocke** [comment]
ha I PR'd to my own fork :) never mind
