### ISSUE TITLE
JavaScript Code Style for gulpfile.js

### ISSUE THREAD

**Issue by antleblanc** [google/web-starter-kit#645]
Hi,

I just installed **SublimeLinter - jscs** plugin to my text editor (ST3).
As you can see here on my screenshot, it shows me an error.

![capture-web-starter-kit](https://cloud.githubusercontent.com/assets/428384/6430055/06345bac-bff9-11e4-96ff-f508a5df7bc8.png)

Error says : Line must be at [80 characteres](https://github.com/jscs-dev/node-jscs/blob/master/presets/google.json#L14).

Do you think we need to make a PR to fix this ?

Thanks!
Antoine

**Comment by arthurvr** [comment]
Yep, that seems like right.

**Comment by addyosmani** [comment]
I think this may still be an issue. We definitely wouldn’t mind a PR to fix this.
