### ISSUE TITLE
<ol> start attribute is not honored by list component

### ISSUE THREAD

**Issue by simshaun** [google/web-starter-kit#648]
The `<ol>` `start` attribute tells the browser what number to begin the list from.

That feature is particularly handy with displaying paginated search results where each page>1 starts at a different number.

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.
