### ISSUE TITLE
Please use flexbox for tabs, avoid padding and margin if possible

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#650]
Your _tabs.scss (including your demo) fails on mobile.

I changed your _tabs.scss slightly:
https://github.com/MikeMitterer/dart-wsk-material/blob/master/lib/sass/tabs/_tabs.scss

No it works on all screens

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.

Please file a new issue on MDL if this still occurs there.
