### ISSUE TITLE
Please use flexbox for wsk-mini-footer, without flexbox it fails on mobile

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#651]
Here is a flexbox-version:
https://github.com/MikeMitterer/dart-wsk-material/blob/master/lib/sass/footer/_mini_footer-flex.scss

Without flexbox you need float: left, float: right... should not be necessary these days.
Flexbox is much more flexible here.
Sample: http://wsk.mikemitterer.at/layout-header-drawer/index.html

**Comment by addyosmani** [comment]
Thanks!/@sgomes can you take a look?

**Comment by sgomes** [comment]
Yup, I'll see what I can do.

**Comment by MikeMitterer** [comment]
You already closed this issue but here: http://wsk.angular.mikemitterer.at/styleguide/index.html#/footer
you can see how the original mini-footer-reacts and the one with flexbox
