### ISSUE TITLE
Missing -webkit-tap-highlight-color on wsk-button shows gray box in mobile browsers

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#653]
Here is what I mean
http://phonegap-tips.com/articles/essential-phonegap-css-webkit-tap-highlight-color.html

![screenshot-1677](https://cloud.githubusercontent.com/assets/116654/6547279/f2d9491a-c5d3-11e4-9e88-5f986c41b4bb.png)

Here is my proposal:
http://goo.gl/7KboM3 (line 85 - 88)

**Comment by MikeMitterer** [comment]
It's not just a problem with buttons - its a problem with all clickable components.
I made a resets/_mobile.scss that sets tap-highlight-color for all these components to transparent.

My proposal:
https://github.com/MikeMitterer/dart-wsk-material/blob/master/lib/sass/resets/_mobile.scss

**Comment by addyosmani** [comment]
We'll be deferring any Material Design component related issues to MDL as we're now just pulling it in directly. If this is still an issue upstream, please feel free to reopen there.
