### ISSUE TITLE
set background-color instead of background for wsk-button--colored

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#656]
On line 168 https://github.com/google/web-starter-kit/blob/0.6.0/material-css-src/app/styleguide/button/_button.scss you set background to $button-fab-color-alt; with this becomes harder to set a SVG background-image via css but if you use background-color instead its much easier to set a svg as background-image.

**Comment by addyosmani** [comment]
Per the other issues, closing in favour of the new CSS library. If still an issue, please file upstream with MDL.
