### ISSUE TITLE
Quote module overlapping text

### ISSUE THREAD

**Issue by joaostein** [google/web-starter-kit#657]
Hey guys,

Just noticed this:

![](https://s3.amazonaws.com/f.cl.ly/items/1I3w0u2i1B2h3a2D2743/Screen%20Shot%202015-03-17%20at%203.16.33%20PM.png)
And was wondering if this is something only on my *end** or a bug actually.  If so, I'd like to know if it's valuable to issue a PR to fix this.

**I'm using Version 43.0.2336.0 canary (64-bit)*

Here is a live demo: https://google.github.io/web-starter-kit/hello-world/styleguide.html#quote

**Comment by battaglr** [comment]
If I'm not mistaken it seems that Roboto font isn't loading, thus the error.

**Comment by addyosmani** [comment]
This appears to be an issue with Roboto not loading indeed. As we've halted work on updating the styles/components for WSK 0.5.0 (0.6 comes with a brand new component set), I recommend using the z-index hack proposed by @battaglr as a workaround in the mean time. Sorry we don't have a better answer for this yet, but 0.6 will have more robust styles :)

**Comment by joaostein** [comment]
hey guys, thanks for the feedback :)
