### ISSUE TITLE
RobotoCondensed-Light.woff Failed to load resource

### ISSUE THREAD

**Issue by processnotproduct** [google/web-starter-kit#666]
I get this in the console no matter what I do, excluding removing the ref. from src of course.

The file is there but it wont load it. Any ideas about why?

fonts/RobotoCondensed-Light.woff Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by dungphanxuan** [comment]
+1 me too

**Comment by fsquaredmedia** [comment]
Try this solution. 

http://stackoverflow.com/questions/4015816/why-is-font-face-throwing-a-404-error-on-woff-files/#answer-4016106

**Comment by boucains** [comment]
The error message reveals the problem - the file can't find the font.

Beginning on line 319 of the main.scss file, you can change the entries (for example) from 

    src: url(fonts/RobotoCondensed-Light.eot);
    to
    src: url('../fonts/RobotoCondensed-Light.eot'); 

and then recompile the SCSS. This is at least one way to fix the problem. Running a W3C checker on the file will help you diagnose the problems and give you insights into fixing them.

**Comment by addyosmani** [comment]
We no longer use a local version of Roboto Condensed in our large rewrite of WSK (0.6.0, out shortly). This issue should no longer be present in master. Sorry for the delay in getting this resolved - we were working on the component library (getmdl.io) meant to replace some of the trickier parts of layout in this project.
