### ISSUE TITLE
Added this project to comparison of starters

### ISSUE THREAD

**Issue by dancancro** [google/web-starter-kit#670]
Hi all,

I'm not sure why I hadn't seen this project before now, but now I have.

I have added a column for this project to my [head-to-head-to-head comparison](https://docs.google.com/spreadsheets/d/1r8rJy2Q5p5QORYKcye93UECwOlSgFL24c5fyF7dqhaM/edit#gid=1607194899) of such things.

Completing the facts in this resource will go a long way in helping relieve the suffering of developers who are confronted with an overwhelming set of options for starting a new project.  It's really hard to know what the trade-offs are between projects but it doesn't have to be.  I've laid all the groundwork for solving this problem and am just looking for experts in each project to disclose what it does and doesn't do.

I've read through the [sales material](https://github.com/google/web-starter-kit/wiki/Why-another-boilerplate%3F) for this project and added YESes/NOs for things I found there, but I'm no web-starter-kit expert and am sure I've missed some things.

So, who would like to help fill in the details about web-starter-kit?  Let me know and I'll add you to the editor list.

Thanks,
Dan

**Comment by addyosmani** [comment]
Thanks for filing this issue and adding us to your comparison list. We're currently working on a newer rework of the project that changes quite a fit pieces. We'll be updating the README as we go on to highlight how we differ from other projects in this same space.
