### ISSUE TITLE
New CSS library

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#674]
We've been working on a new CSS library of components, templates and styles for Web Starter Kit that we'll be launching as a separate project sometime this Summer (tentatively June). 

We've been writing it in-house for the last 6 months (it's looking good!) and we're hoping to switch the repo to public in the proposed timeline.

WSK will start pulling this project in as a dependency. As part of this, we will be deprecating the current Style Guide and closing issues related to the 0.5.x styles. We'll put out an FYI so that new users are aware of upcoming changes.

**Comment by codeandrop** [comment]
Hi @addyosmani, let me know if I can help on this matter or let me know how to prioritize issues to tackle.

**Comment by addyosmani** [comment]
@codeandrop Something that would help us immensely right now is verifying that any of the issues coming in recently are actually fixed by master. If that’s something you think you could help us with, we’d hugely appreciate it :)

**Comment by codeandrop** [comment]
Sure, I can help with that, is there any time range? (issues after January for instance) or labeled issues to check for? I'm going to start with #675 , #677 and #678

**Comment by addyosmani** [comment]
After January would be super helpful :)

**Comment by arthurvr** [comment]
As this threat was never updated: https://github.com/google/material-design-lite/ :tada: :cake:

**Comment by JustJenFelice** [comment]
Has anybody heard anything further about the integration of MDL into WSK? Status?

**Comment by codeandrop** [comment]
we should ask MDL Team or @addyosmani for next steps, let me know if you guys need a hand

**Comment by addyosmani** [comment]
Hey folks. The next steps here are a few PRs to do the following:

* Drop the current style guide and Sass sources
* Replace them in the index.html with CDN references to the latest version of MDL
* Update the index.html layout to use the MDL text template (from 'Templates' on getmdl.io)
* Add a docs mention on how to pull in the MDL Sass sources using npm if you want to use them

Anyone interested in helping with these? You would be a total hero or heroine :star:

**Comment by addyosmani** [comment]
cc @Garbee and @surma as an FYI

**Comment by codeandrop** [comment]
I can start with the first 2, which branch would be the base to start and work over, material-sprint?

**Comment by addyosmani** [comment]
Master please! material-sprint is effectively old prototyping work.

**Comment by arthurvr** [comment]
> material-sprint is effectively old prototyping work.

Do we even have to keep that branch around?

**Comment by addyosmani** [comment]
I was about to ping the team about nixing the branch. Unless there's opposition, let's do this later in the week.

**Comment by addyosmani** [comment]
Master should now contain an MDL'ified version of WSK. We've tested it against both serving and building the project out and the primary piece of work left there is updating the documentation and README to reflect the change.
