### ISSUE TITLE
Bootstrap 3.x variables.scss

### ISSUE THREAD

**Issue by xskif** [google/web-starter-kit#675]
Hi, i'm use Bootstrap with WSK.
When i change variable value in `variables.scss`, provided by Bootstrap Sass 3.x, nothing changes. Terminal shows me the messages like this:
```
[13:32:28] Starting 'styles'...
[13:32:28] 'styles' all files 0 B
[13:32:28] Finished 'styles' after 19 ms
[WSK] Reloading Browsers...
```

For example, if i want change default colors, i need to restart server, that changes take effect.

How can i solve that?

**Comment by Garbee** [comment]
This depends on your gulp setup. You need to make sure changes to that file are being looked for in your style generation and that your style generation task is triggered during the watch task (or whichever task is handling FS watching during serve.)

**Comment by xskif** [comment]
'styles' task starts every time after saving `variables.scss` file or another `.scss` file in styles folder. But it's do nothing.

**Comment by xskif** [comment]
Just tested: after restarting server nothing changes, i need to delete `.tmp` and `dist` folder before.

Folder structure:
```
styles/
    bootstrap/
    components/
    _bootstrap.scss - include all bootstrap components, variables and mixins
    _h5bp.scss
    main.scss
```

```scss
// main.scss contains
@import '_h5bp';
@import 'bootstrap';
```

gulp task by default.

**Comment by addyosmani** [comment]
@Garbee with the latest version in master, could you confirm what happens when you `gulp serve` and make an edit to the `components` directory? I'm currently seeing similar breakage here. Investigating now.

**Comment by xskif** [comment]
@addyosmani confirmed. I was trying to change `box-sizing:` to `padding-box;` in `components/_global.scss` nothing happens. Only messages as usual:
```
[15:31:02] Starting 'styles'...
[15:31:02] 'styles' all files 0 B
[15:31:02] Finished 'styles' after 29 ms
[WSK] Reloading Browsers...
```

**Comment by addyosmani** [comment]
I have some incoming fixes that should help with this.

**Comment by xskif** [comment]
Ok, I look forward

**Comment by xskif** [comment]
I think problem is here:
`gulp.watch(['app/styles/**/*.{scss,css}'], ['styles', reload]);` -- all files

```js
  return gulp.src([
    'app/styles/*.scss',
    'app/styles/**/*.css',
    'app/styles/components/components.scss'
  ])
```
only main.scss, some css and components.scss files compared.

**Comment by addyosmani** [comment]
@xskif FWIW, we've run into issues with gulp-changed in this pipeline before. I may just drop it in https://github.com/google/web-starter-kit/commit/0a02fd912971870009fd08340aa7cf540c147120#diff-b9e12334e9eafd8341a6107dd98510c9L95

**Comment by xskif** [comment]
If there is no other way to fix that, i think you should.
Anyway gulp-changed don't have critical benefits, am i right?

**Comment by codeandrop** [comment]
I tested the current master branch, I added bootstrap and changed variables.scss and it worked. Also I modified some files (_icon-circle.scss and _buttons.scss) inside components folders and it worked as well. @addyosmani and @xskif I think you can close this one.

**Comment by addyosmani** [comment]
Thanks! @xskif we'll reopen this one if you're still unable to use Bootstrap with our setup.

**Comment by xskif** [comment]
All fine with current master. Thanks. Can someone describe me how issue was solved?

**Comment by Garbee** [comment]
[This commit](https://github.com/google/web-starter-kit/commit/0a02fd912971870009fd08340aa7cf540c147120#diff-b9e12334e9eafd8341a6107dd98510c9) was the modifications to fix this. Going though the diff here should provide some insight as to how it was done. I believe the line I commented with "Watch all the things" will be the most likely source of the fix.

**Comment by hugohcn** [comment]
Hello there,

I'm getting the same error :(

Could you help me? It happens sometimes when I change something in my code.

![image](https://cloud.githubusercontent.com/assets/6969705/7601068/4056268a-f8e8-11e4-98df-cfb7746a79eb.png)

**Comment by codeandrop** [comment]
Hi @hugohcn, It looks like a you a have not found custom component, is that the error?, or the system didn't recognize a change in an existing scss file?

**Comment by hugohcn** [comment]
Hi @codeandrop,

The system don't recognize a change that I made. The file is there and this error happen sometimes... :(

Thank you for attention.

**Comment by hugohcn** [comment]
@codeandrop 

I solved the problem enabling the "atomic_save" of Sublime text 3.

It's really weird.

https://github.com/dlmanning/gulp-sass/issues/235

**Comment by codeandrop** [comment]
@hugohcn Yeah, It's a good tip, I was reading that atomic save was the problem when watching files, so it's really weird. I'm glad you fixed the issue.

http://stackoverflow.com/questions/20634684/what-is-sublime-text-doing-when-i-save-a-file
