### ISSUE TITLE
 Error: `libsass` bindings not found.

### ISSUE THREAD

**Issue by wouterkroes** [google/web-starter-kit#677]
After following all installation steps (install.md), 
I get a error when running the gulp serve command.

[14:25:28] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (...\web-starter-kit-0.5.4\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (...\web-starter-kit-0.5.4\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (...\web-starter-kit-0.5.4\node_modules\gulp-sass\index.js:3:17)
    at Module._compile (module.js:449:26)

**Comment by addyosmani** [comment]
Can you try downloading [master](https://github.com/google/web-starter-kit/archive/master.zip) and letting us know if you run into the same issue there?

**Comment by wouterkroes** [comment]
Tried it (again) with the master & still have the same issue
Is it maybe related to https://github.com/yeoman/generator-gulp-webapp#libsass?

* Im on windows, use node v0.11.12 and gulp CLI 3.8.11 and gulp local 3.8.11

**Comment by stevemao** [comment]
I don't think your platform is supported :disappointed:

**Comment by wouterkroes** [comment]
Any idea if my platform will be supported in the future...
This is off course very disappointing news

**Comment by Garbee** [comment]
What would make you think Windows isn't supported @stevemao? It should be fully supported by the toolkit.

@wouterkroes How did you install node? I'd assume with the binary from the website. If so I can boot into a Win 7 machine and attempt to recreate the problem.

**Comment by wouterkroes** [comment]
@Garbee I installed node indeed from the website (https://nodejs.org/).

**Comment by stevemao** [comment]
I mean its probably not supported by libsass.

**Comment by arthurvr** [comment]
> I mean its probably not supported by libsass because of https://travis-ci.org/google/web-starter-kit/jobs/60305614. I'm not 100% sure.

How is the Travis build related to if we support windows or not? Travis isn't even windows.

**Comment by stevemao** [comment]
Just a guess... libsass sometimes seems to fail a lot...

**Comment by codeandrop** [comment]
I tested the following configs: 
1. Windows 8.1, node 0.12.2, gulp 3.8.11 
2. OS X 10.10, node 0.10.29, gulp 3.8.10

After following installation instructions and ran gulp serve it worked (no error on libsass)
 
@addyosmani I think you can close this issue

**Comment by wouterkroes** [comment]
@codeandrop thx voor testing!

When I also use node 0.12.1 it seems to work :+1: 

But does this mean the requirements, for Node, in the readme.md are not correct?
"Node should respond with a version at or above 0.10.x."
Should this be 0.12.x ?

**Comment by Garbee** [comment]
I'll test with 0.10 on Windows 7 in a bit (sorry, crazy weekend didn't get to it sooner.) It could be anything really causing the problem. Node/NPM are notoriously buggy at times with loading stuff.

**Comment by codeandrop** [comment]
@wouterkroes you're welcome! I"m happy to help!

I should work with Node 0.10 and 0.12, if you are on Windows a personal suggestion is to use Docker or Vagrant and setup a virtual machine with Ubuntu (i.e. 14.04) and develop in that environment, you edit your files from Windows like you normally do, but you test in more stable environment like Linux.

@Garbee That's true, please keep me in the loop to see if the issue was fixed.

**Comment by addyosmani** [comment]
It appears this issue is now resolved. Thanks @codeandrop! If @Garbee or others report this is still an issue we'll happily reopen.

**Comment by Garbee** [comment]
I get no errors here. However, I only tested on 0.12 and not 0.10. Went to grab 0.10 and realized it is over 2 years old now for the latest release. You should consider upgrading or running a newer version for WSK.
