### ISSUE TITLE
Slider/Carousel in Google Web Starter Kit

### ISSUE THREAD

**Issue by lojapets** [google/web-starter-kit#681]
How can i add a slider/carousel to web starter kit? Im developing my website and i need that on my homepage. Already tried a lot of ways but without success. I tried Owl carousel, but it never works. Anyone can help me in this issue? Thank you in advance for the attention.
Best regards

**Comment by lukebranch** [comment]
@lojapets ,

I'm not aware of how to put it together with the base web-starter-kit package, however i've got some experience with OwlCarousel and OwlCarousel2.

What problem(s) have you run into with OwlCarousel?

**Comment by lojapets** [comment]
Hi @lukebranch 

Thank you for your reply. I put the code and js/css files correctly but the carousel doesn't work. I cannot identify what's wrong. Maybe there is any incompatibility with web starter kit..i dont know
