### ISSUE TITLE
WSK with PHP files.

### ISSUE THREAD

**Issue by alecsandre** [google/web-starter-kit#686]
Hi. WSK is a great tool and i use it for HTML files.
Now i want to use index.php instead of index.html file in APP directory.
The problem is, that 'gulp serve' command doesn't work. I can see only 'Cannot GET /' on web page. Last thing i tried is described here - http://fettblog.eu/php-browsersync-grunt-gulp/. Doesn't work either.
Please, help me to understand what i am doing wrong.

PS: I am running WSK from desktop (maybe will help somehow).

Thanks.

**Comment by arthurvr** [comment]
Kind of a duplicate of https://github.com/google/web-starter-kit/issues/299.

**Comment by danizord** [comment]
You can use [PHP built-in web](http://php.net/features.commandline.webserver) server instead of `gulp serve`.

**Comment by Garbee** [comment]
Supporting backend languages/systems is out of scope for this projects issue tracker. Please use StackOverflow or other general support resources.

**Comment by patrickjaja** [comment]
Using also WSK with PHP. Just set in a proxy for browsersync and proxy all requests to your local PHP Webserver. When you want to auto reload on changes, have a look to your watch expressions. Besteht regards

**Comment by alecsandre** [comment]
Thank you guys. I'll address this question to StackOverflow auditory. @Garbee is right.
