### ISSUE TITLE
<main ui-view> is reduced to <main>

### ISSUE THREAD

**Issue by dalu** [google/web-starter-kit#690]
When using Angular ui-router and writing `<main ui-view></main>`
the " ui-view" is stripped after running `gulp`.

I don't know how to fix this.

**Comment by douggr** [comment]
Using `data-ui-view` should do the trick

**Comment by Garbee** [comment]
Angular support is out of the scope of this project.

**Comment by dalu** [comment]
@douggr `data-ui-view` works, thanks.
@Garbee not sure if that's an issue of supporting or not supporting angular but more of a filtering non-standard tag properties and the inability or lack of documentation to add custom "tidy" rules.
For instance `ng-submit` in `<form>` or `ui-sref` in `<a>` aren't filtered out, so far, as far as I can tell, the `<main>` tag is affected.
Then, there's the usability question, why would anyone use web-starter-kit to build an optimized output frontend UI when extra properties by, for instance angluar (<insert other frontend lib>), are filtered, resulting in non-working whitespace stripped and minified output. I mean, who builds static html pages anymore nowadays, without added functionality?
Perhaps it's meant for kids, judging by the videos (hand puppets and all).
Just some thoughts.

**Comment by douggr** [comment]
@dalu you're welcome.

Mind closing this? :)

**Comment by dalu** [comment]
@douggr as closed as a nun's ... wardrobe :)
