### ISSUE TITLE
"Native thread-sleep not available." when gulp images

### ISSUE THREAD

**Issue by angusjune** [google/web-starter-kit#691]
Terminal warning:
"Native thread-sleep not available.
This will result in much slower performance.
You should re-install spawn-sync if possible."
And the images won't be copied to directory app.

Tried to re-install spawn-sync, but didn't fix the problem.

**Comment by TatsuyaHishima** [comment]
I'm in same problem and found how to remove the warning.

```
npm list
```
would shows you need "try-thread-sleep" to use spawn-sync.

So, add bellow in your package.json and "npm install" again.

```
"try-thread-sleep": "^1.0.0",
```

**Comment by rizqinizamil** [comment]
Solved after installing <code>try-thread-sleep</code>

**Comment by doomsbuster** [comment]
@TatsuyaHishima and @rizqinizamil thanks for you inputs. I ran the npm list and it clearly indicated the error 
`npm ERR! missing: try-thread-sleep@^1.0.0, required by spawn-sync@1.0.13
npm ERR! missing: try-thread-sleep@^1.0.0, required by spawn-sync@1.0.11
npm ERR! not ok code 0
`
I installed try-thread-sleep and the error went away.

**Comment by addyosmani** [comment]
For anyone that runs into this in future, the resolution is:

1. Upgrade to node@0.12 or node 4
2. Install try-thread-sleep as a dependency of your app directly.

It should no longer be an issue in master.

**Comment by zhilevan** [comment]
Worked for me too . tnx
