### ISSUE TITLE
add WSK to CMS 

### ISSUE THREAD

**Issue by lojapets** [google/web-starter-kit#693]
Any chance to add wsk to Content Management System?
If anyone knows how, please share..

Best regards

**Comment by Garbee** [comment]
This is out of the scope of what we support. You are free to do whatever you want with WSK, including integrate into a CMS project.

Please look for help with this in a support channel for whatever CMS you use.

**Comment by lojapets** [comment]
@Garbee you're right, my bad..sorry, it was not my intention..I'll close this issue.
