### ISSUE TITLE
Error using npm install to get web-starter-kit as devDependencies

### ISSUE THREAD

**Issue by garmr** [google/web-starter-kit#694]
Hello,

First, web-starter-kit is definately a really usefull start for web templates and I enjoy using it :) 

Now for this issue : could you possibly add a "name" property in package.json ?
When I try to npm install this repo, npm exit with an error "No name provided" and it looks like this issue is related to this missing property.

Cheers :)

**Comment by Garbee** [comment]
You are not meant to pull this in as a dependency. It is meant to be cloned and used directly as your kick-start project structure.

**Comment by garmr** [comment]
Ok, fine I wasn't aware of this issue.
I'm closing this one :)
