### ISSUE TITLE
Bump sw-precache

### ISSUE THREAD

**Issue by stevemao** [google/web-starter-kit#695]
This should be bumped up to "^1.3.2" to ensure that the logging changes described at 385fa96#commitcomment-11126343 are picked up.

Ref: https://github.com/google/web-starter-kit/commit/385fa962690404634ee5e1caf1727421c6f6851f

**Comment by addyosmani** [comment]
Thanks for filing all these bugs!

**Comment by stevemao** [comment]
My pleasure :smile:
