### ISSUE TITLE
Use jscs to enforce styles

### ISSUE THREAD

**Issue by stevemao** [google/web-starter-kit#697]
I notice some have two new lines after a task but some have one. Should we make them consistent? a jscs rule can help. 

Some are missing a `;`.

In comment `// Remove Any Unused CSS` "A" and "U" should be lowercase?

Some strings are using double quotes.

Line 22
`// Include Gulp & tools we'll use`
"Gulp" should be "gulp"?
https://github.com/gulpjs/gulp/blob/master/docs/FAQ.md#is-it-gulp-or-gulp

Ref: https://github.com/google/web-starter-kit/commit/0a02fd912971870009fd08340aa7cf540c147120

Since this module is under google, why "preset": "google" cannot define all the style rules?
And also why there's no jscs task in gulp but only jshint? IMO they are equally important. Thanks 

Ref: https://github.com/google/web-starter-kit/commit/208b44e0864bb215a36220445cd6c67a4d804eb0

**Comment by stevemao** [comment]
Sorry this is probably very fiddly.

**Comment by stevemao** [comment]
There is an extra `,`.

Ref: https://github.com/google/web-starter-kit/commit/8a96128fbbb66fe6ac99471c475e4af27d8e252c

**Comment by arthurvr** [comment]
As I mentioned somewhere earlier, I'd prefer to switch to ESLint and drop JSCS and JSHint altogether.

**Comment by nicolasgarnier** [comment]
Lets open a separate issue for comparing ESLint to JSCS/JSHint and take a decision.
Lets open a separate issue for adding a JSCS gulp task as well.

The rest seems to have ben taken care of in https://github.com/google/web-starter-kit/commit/70c9773979a6e57fcb7c56becb9c2224aa41da2b
