### ISSUE TITLE
WSK style guide does not follow Web-Fundamentals style guide 

### ISSUE THREAD

**Issue by code-guru** [google/web-starter-kit#701]
The given style guide in Web-Starter-Kit does not follow Web-Fundemental style guide completely.

Styleguide comes with WSK seems to be a messed up and broken version of WebFundemental.

For example:
  - WSK has 20 items, where WF has 26.
  - The links are not underlined in WF, where in WSK they are.
  - In WSK 'List' section, dl tag is not declared, where in WF it is.
  - In WSK color section, gray-medium(WF) is not declared.
  - ...

There are also some issues in WF styleguide, which should be reported to WF repo.

Regards

**Comment by addyosmani** [comment]
Agreed. The WSK style guide is deprecated as is. A brand new version based on Material Design  has been in the works for the last quarter and we hope to have it out the door in June. No updates are planned for the current style guide here.

**Comment by code-guru** [comment]
Thanks for clarification, that was quick :grinning:
