### ISSUE TITLE
Can anyone run he gulp file tasks without errrors?

### ISSUE THREAD

**Issue by Itagiba** [google/web-starter-kit#707]
I have been trying to work with the web-starter-kit both static and angular versions but I keep running into the same errors time and time again whenever I run the scripts task. 

// Build Production Files, the Default Task
gulp.task('default', ['clean'], function(cb) {
	runSequence('styles', 'vendor', 'scripts', ['jshint', 'html', 'images', 'fonts', 'copy'
], cb);
});

The errors I will get are either:
 TypeError: undefined is not a function (relating to HTML task) 

or something along the lines of:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new JS_Parse_Error (C:\Users\Jensten\webkit\node_modules\gulp
-uglify\node_modules\uglify-js\lib\parse.js:196:18)
    at js_error (C:\Users\Jensten\webkit\node_modules\gulp-uglify\no
de_modules\uglify-js\lib\parse.js:204:11)

I have seen the issue above in other threads, tried the solutions offered i.e.
- downloaded newer versions of modules
- uncommented the line from the HTML function     .pipe($.if('*.css', $.uncss({
      html: [
        'app/index.html'
      ],
- deleted the entire node_modules and doing npm install again but nothing compiles except sass.

Is there a clean version of web-kit that does not throw errors? All I need is the following:

- SASS compiler/watch
- JS and CSS minifier
- output all files to a clean set of directories every time he project is served (icluding fonts)
- angular

I think that is pretty much it. There are a lot of tasks I cannot quite understand in the gulpfile.js as the documentation is pretty basic. Has anyone encountered an resolved any of the issues above?

**Comment by dsebastien** [comment]
Hey there. You might want to take a look at my current build (https://github.com/dsebastien/midnightLightV2); I'm still iterating on it but it's working quite well. I've started off of Web Starter Kit, fixed some annoying issues, added documentation and adapted it to my own needs which are fairly similar to yours apart from the fact that I'm using TypeScript in addition (and some other goodies ~~). I've listed the major changes that I've made over here as some of these might be useful for others: https://github.com/google/web-starter-kit/issues/704

**Comment by Itagiba** [comment]
Hey, thanks a lot for this. I ended up trying to build the whole thing from
scratch which is proving to be really slow as I am a beginner but good
education nevertheless. I will definitely check out your project if(when)
mine breaks as I have been looking all over the place for a clean project
skeleton using the using the angular/gulp/sass/bootstrap-ui(no jquery)
combo.

Do you know of any good straightforward blogging engines we can plug in
without having to implement lots of third parties?

Cheers

**Comment by addyosmani** [comment]
Could you share some more information about what OS you're on and what version of Node you have locally? Were there any changes made to the Gulpfile/setup prior to running the tasks?

**Comment by Itagiba** [comment]
Hey apologies, I just got this. I need to work on both MAC and Windows 7
(home and work) and unfortunately I am unable to share my repo.  I am
trying to set up gulp tasks to export

*from the root (also contains angular-ui templates, bower_components, gulp,
package.json files etc.):*
*---views/*
-----------view1.html
-----------view1.js
*----src/*
--------img
--------js
--------sass
-----index.html (app)
-----apps.js
*-----app/*



*To a clean non-angular dependent directory with minified css/js files*
*------------app/*
-----------------index.html
*-----------------assets/*
-------------------------css
-------------------------fonts
-------------------------images
-------------------------scripts

*My gulp file has been created from scratch and I use the sync task to
update the directories but I am still figuring out a better way*:

//Gulp pluginvar gulp = require("gulp"),//http://gulpjs.com/ util = require(
"gulp-util"),//https://github.com/gulpjs/gulp-util sass = require("gulp-sass
"),//https://www.npmjs.org/package/gulp-sass autoprefixer = require('
gulp-autoprefixer'),//https://www.npmjs.org/package/gulp-autoprefixer
minifycss = require('gulp-minify-css'),//
https://www.npmjs.org/package/gulp-minify-css rename = require('gulp-rename'
),//https://www.npmjs.org/package/gulp-rename connect = require ('
gulp-connect'), jshint = require('gulp-jshint'), sourcemaps = require('
gulp-sourcemaps'), imagemin = require('gulp-imagemin'), browserSync =
require('browser-sync'), reload = browserSync.reload; open = require ('
gulp-open'), uglify = require ('gulp-uglify'), notify = require ('
gulp-notify'), concat = require ('gulp-concat'), imagemin = require('
gulp-imagemin'); pngquant = require('imagemin-pngquant'); log =
util.log; //Global
Variablesvar sassFiles = "src/sass/**/*.scss";var varBaseDir = "./app/"  //
paths to assetsvar paths = { styles: [ 'app/assets/styles/vendor/**/*.css',
'app/assets/styles/**/*.css', 'app/assets/styles/**/*.sass' ], scripts: {
coffee: [ 'app/assets/scripts/**/*.coffee' ], js: [ 'src/js/*' ] }, images:
[ 'src/img/**/*' ], fonts: [ 'fonts/**/*' ]}; // Copy Web Fonts To app
productiongulp.task('fonts', function() { return gulp.src(paths.fonts)
.pipe(gulp.dest('app/assets/fonts')) .pipe(notify({ message: 'All fonts
generated' }));}); //Optimise graphics and imagesgulp.task('images',
function () { return gulp.src(paths.images) .pipe(imagemin({ progressive:
true, svgoPlugins: [{removeViewBox: false}], use: [pngquant()] }))
.pipe(gulp.dest('app/assets/images')) .pipe(notify({ message: 'Images ready
for distribution' }));}); //Synching Relative to gulp file// Watch Files
For Changes & Reloadgulp.task('sync', function() { browserSync({ open: "
local", browser:'chrome', notify: true, server: { baseDir: "app/", directory
:false, index:"index.html", routes: { "/bower_components": "bower_components
", "/app/views": "views" } } }); gulp.watch(['index.html'], reload); gulp.
watch(['**/*.html'], reload); gulp.watch(['../sass/'], ['sass']); gulp.watch
(['scripts/**/*.js'], ['scripts', reload]); gulp.watch(['assets/images/**/*'],
reload);}); //launch browsergulp.task('serve', ['sync']); //Generate
stylesheets fro sass filesgulp.task("sass", function(){ log("Generate CSS
files " + (new Date()).toString()); gulp.src(sassFiles) .pipe(sass({ style:
'expanded' })) .pipe(autoprefixer("last 3 version","safari 5", "ie 8", "ie 9
")) .pipe(gulp.dest("app/assets/css")) .pipe(rename({suffix: '.min'}))
.pipe(minifycss()) .pipe(gulp.dest('app/assets/css'));}); //Watch files for
changesgulp.task("watch", function(){ log("Watching scss files for
modifications"); gulp.watch(sassFiles, ["sass"]);}); // HTML Taskgulp.task('
html', function(){ gulp.src('app/**/*.html') .on('error', console.error
.bind(console)) .pipe(gulp.dest('.')) .pipe(connect.reload());}); //
Scripts Task (Uglifies)--example 1gulp.task('scripts1', function(){ gulp.src
(paths.scripts.js) .pipe(uglify()) .on('error', console.error.bind(console))
.pipe(jshint()) .pipe(rename({suffix: '.min'})) .pipe(gulp.dest('
app/assets/scripts/')) .pipe(connect.reload()) .pipe(notify({ message:
'Finished
minifying JavaScript'}));}); gulp.task('scripts', function() { return gulp.
src('app/scripts/**/*.js') .pipe($.if('*.js', $.uglify({preserveComments: '
some'}))) .pipe($.sourcemaps.init()) .pipe($.concat('app.js'))
.pipe($.sourcemaps.write('./'))
.pipe(gulp.dest('app/assets/scripts'));}); //gulp.task('default',
['html', 'styles', 'scripts', 'images', 'connect', 'watch', 'open']);
gulp.task('default', ['sass', 'sync','html','serve']);


The blog will come after but right now my priority is to generate the app
folder with everything I need.

I hope this is clear.

thanks

**Comment by Garbee** [comment]
> *My gulp file has been created from scratch and I use the sync task to
update the directories but I am still figuring out a better way*

This is out of the scope of support for the issue tracker. Try asking on StackOverflow or other reputable support sites for help here.

Looking at the original comment though, it doesn't seem to be an error with the HTML step but the scripts step since it is dealing with uglifying the scripts. So maybe you have modified something in your script and that is causing the problem.

**Comment by Itagiba** [comment]
No worries, thanks.
