### ISSUE TITLE
generate SW breaks if you remove index.html

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#715]
Just had a project where I am using templates, removed the index.html file and the entire build broke because the SW generation task expected index.html to exist.

Could we get to a point where the service worker generation reads the files in dist/ and generates the SW based on that rather than having a reliance / expectation on particular files?

**Comment by addyosmani** [comment]
cc @jeffposnick for his take on the second part of your comment

**Comment by addyosmani** [comment]
Addressed in https://github.com/google/web-starter-kit/pull/719
