### ISSUE TITLE
Forum to discuss usage - Hamburger Menu

### ISSUE THREAD

**Issue by clmarshall** [google/web-starter-kit#720]
I am looking for a way to make the hamburger icon and the ability to open/close it available in all resolutions. I cannot seem to find any discussion forums for the Web Starter Kit to ask this type of question.

I want my app to have that menu functionality, and cannot seem to determine what turns that menu button off at higher resolutions.

**Comment by Garbee** [comment]
This is possible in Material Design Lite which is launching soon and will be used in the next WSK release.

**Comment by clmarshall** [comment]
Thanks Garbee - Good to know!

Still, it would be good to have a place to discuss usage. Is there some place carved out in Google Message boards or forums that I'm not aware of?

**Comment by addyosmani** [comment]
Are you wanting to discuss hamburger menus as a general UX pattern? (as in, outside of specific implementations in the Material Design spec?)

**Comment by addyosmani** [comment]
Deferring to Material Design Lite for usage discussions on UI patterns implemented. WSK is going to focus on delivering a good starting point using existing tools rather than trying to do anything different on the UI front.
