### ISSUE TITLE
Inconsistent use of useref build blocks

### ISSUE THREAD

**Issue by callumlocke** [google/web-starter-kit#723]
styleguide.html [has a build block for CSS](https://github.com/google/web-starter-kit/blob/0b94f55fa3d21ef28df916672b63dac919c633d3/app/styleguide.html#L11-L13) but index.html [does not](https://github.com/google/web-starter-kit/blob/0b94f55fa3d21ef28df916672b63dac919c633d3/app/index.html#L36)

**Comment by addyosmani** [comment]
You're absolutely right. As part of our refactor for #674, we'll be dropping the current styleguide and should ensure we're consistent with where and if we're using useref blocks.

**Comment by stevemao** [comment]
I have raised the same issue https://github.com/google/web-starter-kit/issues/597

**Comment by callumlocke** [comment]
Closing this as styleguide.html is gone!
