### ISSUE TITLE
Requiring external module babel/register

### ISSUE THREAD

**Issue by nomadme** [google/web-starter-kit#726]
After cloning and 

```
npm install
```

and checking gulp -v, gives me babel-core/register is failing.

```
gulp -v
[13:42:46] Failed to load external module babel-core/register
[13:42:46] Requiring external module babel/register
[13:42:46] CLI version 3.9.0
[13:42:46] Local version 3.9.0
```

when I check 
```
npm ls babel

└── babel@5.6.14
```
what am I doing wrong?

**Comment by arthurvr** [comment]
PR with a fix: #727

**Comment by alphapilgrim** [comment]
When i run gulp serve i get this error: 

Requiring external module babel-register

Im getting this error when I try to run npm ls label, and I have ran : 
npm cache clean, npm unistall gulp , npm install -g gulp 

 $ npm ls babel
└── (empty)

npm ERR! code 1

Any idea's?

**Comment by andretf** [comment]
try `npm install --save-dev babel-register`.

**Comment by andretf** [comment]
also, `babel` was renamed to `babel-core`, you should check with `npm ls babel-core` instead.

**Comment by llwang8** [comment]
I tried HECTORkaizen's method.  all showing the same.  But "gulp" still not working.  
 "Requiring external module babel-core/register"
Any more suggestion?

**Comment by cesards** [comment]
@llwang8 same problem here :-/

https://github.com/google/web-starter-kit/issues/878

**Comment by darpanrangari** [comment]
same issue

 Requiring external module babel-register
gulpfile.babel.js:26
import fs from 'fs';

**Comment by naimlatifi5** [comment]
Same issue!

**Comment by AfvanMoopen** [comment]
same issue
