### ISSUE TITLE
Getting Warnings in Installation

### ISSUE THREAD

**Issue by sahilbabbar** [google/web-starter-kit#729]
![screen shot 2015-07-15 at 4 58 12 pm](https://cloud.githubusercontent.com/assets/6317330/8697896/bf2338e4-2b16-11e5-923c-c0fbf3e1653d.png)

**Comment by arthurvr** [comment]
Those are warnings, not errors. Does everything work as expected when running the build setup?

**Comment by sindresorhus** [comment]
Don't run it with sudo.

**Comment by sahilbabbar** [comment]
If it is run without sudo then it doesn't work and says to run with sudo.

**Comment by sindresorhus** [comment]
Use https://github.com/npm/npm/issues for npm support.
