### ISSUE TITLE
package.json should depend on "babel", not "babel-core"

### ISSUE THREAD

**Issue by callumlocke** [google/web-starter-kit#731]
If you try to run any gulp task without having installed `babel` on your system, you get:

```
[14:37:50] Failed to load external module babel/register
~/code/foo/gulpfile.babel.js:25
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
```

The package.json includes `babel-core`, which is not being used AFAICT, so I'm assuming this was supposed to be `babel`.

**Comment by arthurvr** [comment]
See https://github.com/google/web-starter-kit/pull/727, you're likely just on an old gulp version.

**Comment by arthurvr** [comment]
Try updating your global gulp:

```
npm install -g gulp
```

**Comment by callumlocke** [comment]
Oh cool, I didn't know babel-core had `/register` in it, thanks

**Comment by arthurvr** [comment]
So then I guess this issue can be closed?

**Comment by callumlocke** [comment]
Thought I did
