### ISSUE TITLE
styleguide.html fails W3C check in styleguide_icons section

### ISSUE THREAD

**Issue by boucains** [google/web-starter-kit#735]
Existing HTML in the Icons section of the Styleguide throws a "closing tag matches nothing" error on a W3C validity check.

Existing code example

    <div class="g--third g--last">
        <p><div class="code-sample"><i class="icon icon-star"></i></div></p>
    </div>

Potential solution example

    <div class="g--third g--last">
         <p>
            <span class="code-sample">
               <i class="icon icon-star"></i>
            </span>
        </p>
    </div>

**Comment by addyosmani** [comment]
As part of our move to #674, which just landed, the legacy styleguide has now been dropped. We are no longer supporting that particular component of WSK.
