### ISSUE TITLE
iOS 8 Scrolling Header Issue

### ISSUE THREAD

**Issue by TheTannerRyan** [google/web-starter-kit#751]
I have noticed that there is a bug with the fixed header and the hamburger menu on iPhones. I have an iPhone 5S, so I do not know if the issue affects other iPhones. 

The issue can be seen with my [website](http://www.hamiltonweather.ca/). The the menu operates perfectly normal when the there hasn't been any vertical scroll, but as soon as you scroll down and then try to open the menu, both the menu and header shifts upwards and becomes obstructed.

It also seems that others are having issues: [link](http://stackoverflow.com/questions/26391059/new-fixed-position-bug-on-ios8).

Considering the great usage of iOS 8, is there any fix to this?

**Comment by addyosmani** [comment]
The version of the layout you are currently using has been superseded by http://getmdl.io, which is a project we've been building for the last year to replace our layout and components. The current version of WSK won't be addressing issues with the older layout system (really sorry), but where possible we recommend using Material Design Lite's layout instead.
