### ISSUE TITLE
Requiring external module babel-core/register

### ISSUE THREAD

**Issue by PSS-Mike** [google/web-starter-kit#759]
I've looked at the various other comments regarding this issue, and none of the proposed solutions seem to be working for me. 

```
node -v
v4.1.2
```

```
gulp -v
Requiring external module babel-core/register
CLI version 3.9.0
Local version 3.9.0
```

```
npm -v
2.14.4
```

I've deleted node_modules folder and reinstalled using npm install, which works successfully except doesn't resolve the error. I've also reinstalled everything above, including gulp and node globally, still no success. I've also tried reverting to node 0.12, as I found one comment stating some modules haven't been updated to work with 4.x, still no luck.

I'm unsure of what to do at this point, as none of the Scripts task seems to work, though the rest of the gulpfile processes fine.

**Comment by PSS-Mike** [comment]
I discovered the issue wasn't with babel after all. For some reason the Scripts task from cloning the repo doesn't match the task in the gulpfile linked on here. I copied the gulpfile from here into my directory and the task now works.

**Comment by monkick** [comment]
I had same problem.
but, resolved

```
$ cat package.json

{
  "devDependencies": {
    "apache-server-configs": "^2.7.1",
    "babel-core": "^6.0.15",
    ...
```
↓

```
{
  "devDependencies": {
    "apache-server-configs": "^2.7.1",
    "babel": "^6.0.15",
    ...
```
