### ISSUE TITLE
Do the icons still need to be in this repo?

### ISSUE THREAD

**Issue by callumlocke** [google/web-starter-kit#760]
The files in [app/images/icons](https://github.com/google/web-starter-kit/tree/master/app/images/icons) don't appear to be used anywhere, and they don't all build correctly anyway.

Were they supposed to be removed along with the style guide?

**Comment by addyosmani** [comment]
Well spotted! We can now remove these too. They should have been nixed with the style guide. Thanks @callumlocke :candy:
