### ISSUE TITLE
gulp-size is reporting an unexpected value (optimized files plus sourcemap files)

### ISSUE THREAD

**Issue by robwierzbowski** [google/web-starter-kit#764]
`gulp-size` is incorrectly reporting size when sourcemap files are generated (scripts and styles tasks). Well, it's reporting correctly but probably not what users expect.

Currently: 
![image](https://cloud.githubusercontent.com/assets/925735/10740872/03dd86b2-7bfb-11e5-88be-87a92417c6ed.png)

OS reported CSS file size: 
![image](https://cloud.githubusercontent.com/assets/925735/10740855/ee6567dc-7bfa-11e5-82f6-0cb0ba513950.png)

With `showFiles: true`: 
![image](https://cloud.githubusercontent.com/assets/925735/10740819/b58522c2-7bfa-11e5-8de2-6d9ca672c2d4.png)

I can write a PR to fix this. Any ideas to filter the maps without adding too much complexity to the gulpfile? My initial thoughts are either to call `size` before writing sourcemaps, or to use `gulp-ignore`. I think the former is preferable because it avoids new dependencies.

**Comment by robwierzbowski** [comment]
So the tasks that write sourcemaps would look more like this:

```js
    // Concatenate and minify styles
    .pipe($.if('*.css', $.minifyCss()))
    .pipe($.size({title: 'styles'}));
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('dist/styles'))
});
```

**Comment by harley22** [comment]
I don't have a clue what you are talking about!!??
