### ISSUE TITLE
Unnecessary dep?

### ISSUE THREAD

**Issue by ramasilveyra** [google/web-starter-kit#777]
Is `require-dir` still necessary? It was used when all gulp task were in split files.

**Comment by ramasilveyra** [comment]
I found on `gulpfile.babel.js`

````
// Load custom tasks from the `tasks` directory
// try { require('require-dir')('tasks'); } catch (err) { console.error(err); }
```

**Comment by arthurvr** [comment]
Maybe we should just append the `npm install` command for the dependency in those comments and drop the dep for now. I don't see that much people using the `tasks` directory thing so I guess it's a moot dependency for most.

**Comment by Garbee** [comment]
I think we should move towards using that structure by default, as we are with MDL in the future. Having the gulp  tasks reside in their own files is a nice and simple enhancement.

**Comment by robwierzbowski** [comment]
++ to @arthurvr's suggestion. For a sub 1000 line gulpfile, especially with the secondary purpose of introducing people to gulp, I think a single file is easier to grok and play around with.
