### ISSUE TITLE
Publishing Web Starter Kit onto AWS elastic beanstalk

### ISSUE THREAD

**Issue by quaintcow** [google/web-starter-kit#779]
I couldn't find much on the internet about how to do this. 

Does anyone have experience doing this? I can't get it working. 

Error message: "No start scripts located in package.json. Node.js may have issues starting. Add start scripts or place code in a file named server.js or app.js."

**Comment by addyosmani** [comment]
After you're setup the project and installed our dependencies, you should just be able to create a production build by running `gulp` and then deploy the contents of the `dist` to AWS. There's a guide over at https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/aws-s3-deployment.md that should be able to help you get mostly there.
