### ISSUE TITLE
Update `browser-support` section from `README.md`

### ISSUE THREAD

**Issue by alrra** [google/web-starter-kit#790]
The [`browser-support`](https://github.com/google/web-starter-kit/blob/c1acc01b928fed64168d5a6606aacc36af2214a1/README.md#browser-support) section is kinda outdated. 

![](https://cloud.githubusercontent.com/assets/1223565/11614526/183eb5a4-9c4e-11e5-9cf0-99863ba85bad.png)

--

Things to consider:

   * Add the [Edge](https://www.microsoft.com/en-us/windows/microsoft-edge) browser to the browser support list
   * [Not using exact version numbers where possible as they rapidly get outdated](
https://github.com/h5bp/html5-boilerplate/pull/1682#issuecomment-78923132)

Cc: @addyosmani.

**Comment by addyosmani** [comment]
Very well pointed out. Agree we should update that section and definitely cover Edge too. Thanks @alrra!
