### ISSUE TITLE
Addressing Context

### ISSUE THREAD

**Issue by darcyclarke** [google/web-starter-kit#8]
There's a number of ways you can build a multi-device project. That said, from my experience, you don't always want to ship the same experience for every **context**.

It goes without saying, the more you know about a user's environment the better equipped you are to serve an optimal experience.

I'm wondering: Will we reference or include projects that look to provide insight to context? (like the few I've listed below) Also, will we try to standardize or consolidate a design approach for developing with context in mind? I think this project would be perfect to do just that.

The below are a number of examples to approach developing an experience based on a unique context. I think we could definitely work to provide a standard way to develop with these tools or structure your project to best tackle this issue.
#### IE conditional comments (browser detection)

``` html
<!--[if IE]><html class="ie"><![endif]-->
```

``` css
.ie .component { ... }
```
#### @media queries (viewport detection)

``` css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .component { ... }
}
```
#### @supports (feature detection)

``` css
@supports (animation-name: test) {
  .component { ... }
}
```
#### matchMedia() (feature detection) https://github.com/paulirish/matchMedia.js

``` javascript
if( matchMedia('tv').matches ) { ... }
```
#### Modernizr (feature detection) https://github.com/Modernizr/Modernizr

``` javascript
if ( Modernizr.touch ) { ... }
```
#### UA-Parser (browser, os & device detection) https://github.com/tobie/ua-parser

``` javascript
var r = require('ua-parser').parse(navigator.userAgent);
if ( r.device.family.toLowerCase() == 'iphone' ) { ... }
```

**Comment by gauntface** [comment]
I'm going to close this issue (Sorry - I know it's a crappy thing to do).

I feel like if WSK blocks developers from doing any of the above, it's an issue. But directing users to actively do these patterns is ultimately not WSK's place. It will depend on the web app and the developers requirements and experience.
