### ISSUE TITLE
Header is NOT responsive

### ISSUE THREAD

**Issue by ahmadimt** [google/web-starter-kit#801]
Hi,

I am trying web-starter-kit-0.6.0. When I do gulp server, the page comes up, the header part is not responsive.

Please refer the screen shot attached.
![screenshot from 2015-12-25 18 15 09](https://cloud.githubusercontent.com/assets/10077189/12002929/ca1aa01e-ab33-11e5-8306-ceac46194e55.png)

Thanks,
Imteyaz Ahmad

**Comment by Garbee** [comment]
What do you expect exactly?

**Comment by ahmadimt** [comment]
Hi Garbee,

In desktop view, we get "TECHNOLOGY" and "FAQ" section like below

![image](https://cloud.githubusercontent.com/assets/10077189/12003083/f5ed3518-ab37-11e5-8634-e626821cd815.png)

but on re-sizing it, only "TECHN"  from "TECHNOLOGY" is visible and "FAQ" section is NOT visible at all.

Thanks,
Imteyaz Ahmad

**Comment by Garbee** [comment]
It is working as expected. You need to press & scroll to see the rest of the menu.

On a side note: [Device Mode](https://developers.google.com/web/tools/chrome-devtools/iterate/device-mode/?hl=en) is way better for mobile testing than resizing the viewport. Check it out if you haven't already.

**Comment by CharlJKruger** [comment]
I see what you mean by press and scroll however there really should be some indication to the user that they could scroll the nav horizontally. e.g. first time they visit the site and it's on a mobile device, they would never know that there where other top level pages.

**Comment by Garbee** [comment]
[The spec](https://www.google.com/design/spec/components/tabs.html#) shows we *shouldn't* have an indicator on mobile. However, we should have something on desktop for users to interact with.

File an issue upstream with [Material Design Lite](https://github.com/Google/Material-Design-Lite) and we can try to get that part fixed. Nothing WSK can do about it since it is simply requiring MDL as a dep for base styling.

**Comment by addyosmani** [comment]
Closing as an MDL issue. Ideally, all Material Lite related bugs and feature requests should be filed upstream please :+1:
