### ISSUE TITLE
Replace gulp-minify-html with gulp-htmlmin

### ISSUE THREAD

**Issue by vtambourine** [google/web-starter-kit#802]
Gulp plugin `gulp-minify-html` got [deprecated](https://github.com/murphydanger/gulp-minify-html/commit/c9e992c36cb528816341cb675f360c1865723d78). Probably, it worth now to switch to recommended [gulp-htmlmin](https://github.com/jonschlinkert/gulp-htmlmin)?

**Comment by robwierzbowski** [comment]
I'll do a little PR to take care of this and minify-css -> cssnano.
