### ISSUE TITLE
Console Error http://localhost:3000/service-worker.js net::ERR_FILE_EXISTS

### ISSUE THREAD

**Issue by lodestarops** [google/web-starter-kit#807]
Hey Guys,

HAPPY NEW YEAR! First of all GREAT update! I've been waiting for this release for awhile to put into my dev workflow. I'm loving all the new documentation and the move to ESLint as well. Thank you!

**Issue:**
I'm noticing an issue in my Chrome Dev Console it's showing:
[CURRENT DATE]:3000/service-worker.js:1 GET http://localhost:3000/service-worker.js net::ERR_FILE_EXISTS

**Repro Steps:**
I just downloaded wsk0.6.0 release:
https://github.com/google/web-starter-kit/releases/tag/v0.6.0

**Ran:**
npm install

**There were some warnings about using depreciated dependencies:**
npm WARN deprecated gulp-minify-html@1.0.5: Consider using gulp-htmlmin instead
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
npm WARN peerDependencies The peer dependency eslint@>=1.8.0 included from eslint-config-google will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@>=1.7.3 included from eslint-config-xo will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN deprecated lodash@1.1.1: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

**Expected Behavior:**
Load my localhost:3000 and localhost:3000/basic.html and start building away!! However I'm seeing an error in my devtools, console:

![screen shot 2016-01-04 at 4 01 50 pm](https://cloud.githubusercontent.com/assets/14285793/12104046/92a4aa00-b2fc-11e5-91dc-660e5b748eba.png)

**Current Behavior:**
Everything seems to work fine, however, I've been trained the hardway to make sure there are *no console errors* before moving on with build (since you never know what a JS error could be doing to your site). 

**Comments**
Any ideas on what could be causing this? Or how I would go about fixing?

**Comment by Garbee** [comment]
Doing a quick google search for the error reveals an [upstream bug](https://code.google.com/p/chromium/issues/detail?id=541797) for this error. Also an [accompanying SO post](http://stackoverflow.com/questions/33328579/service-worker-throwing-an-neterr-file-exists-error) on the same thing. Just keep on working.

**Comment by lodestarops** [comment]
Thanks @Garbee I saw that it was a Chromium issue, wasn't sure how it would affect builds, but as stated it seems, looks like a non-issue now that I've read the doc more closely. Thanks G!

**Comment by thebiltheory** [comment]
Is there a fix for this? It's so annoying even tho we can ignore this.

**Comment by lockerfish** [comment]
So, here is a fix go to chrome://serviceworker-internals/ and unregister any service worker to localhost
