### ISSUE TITLE
drawer and header incorrect display until material.min.js loaded

### ISSUE THREAD

**Issue by hir3npatel** [google/web-starter-kit#808]
I am showing a drawer on smaller screens and otherwise some navs in the header on large screens. I load a few images on every page, which means when the page comes up the header is not structured correctly until the browser gets to loading material.min.js. Since I am loading images in the page body, fetching of material.min.js seems to wait until the images are fetched. While the images are fetching, the header of the page looks broken on small screen. Only once material.min.js fetches and loads does the header/drawer render correctly.

eg. go to phone screen size, set the connection type to 3g or 2g and try load this page (http://104.197.182.186/gallery.html). Watch the header/drawer as the browser fetches the images, and then after it has fetched all of them.

**Comment by Garbee** [comment]
Known issue in MDL with V1 layout having so much dependent in JS. This is being fixed with 2.0's big layout overhaul. Nothing we can do in 1.x, just something you need to develop with in mind and try to minimize the damage.

**Comment by hir3npatel** [comment]
Okay, thanks for the info. I will keep a look out for v2 then.

**Comment by addyosmani** [comment]
Closing as an upstream issue. We'll move this over to using MDL 2.0 when it's ready :cake:
