### ISSUE TITLE
So many outdated/deprecated dependencies?

### ISSUE THREAD

**Issue by nguyenvietvinhse** [google/web-starter-kit#815]
When I try to install Google Web Starter Kit, I got these:

npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN deprecated lodash@1.1.1: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm

Is it normal?

**Comment by dandv** [comment]
I get the same warnings, plus several other errors. Also, `npm install` takes ~6 minutes.

**Comment by Suchitkushwaha** [comment]
try this npm install -g npm

**Comment by Suchitkushwaha** [comment]
Try this   npm -g install npm

**Comment by surma** [comment]
> Is it normal?

Sadly, yes. For now, we are living with these warnings, as we would be introducing compatibility issues otherwise.
In our continued effort towards v2 of WSK, we have no warnings (so far) and have extended our CI setup to inform us about outdated dependencies.
