### ISSUE TITLE
ERR_INSECURE_RESPONSE when registering service-worker. 

### ISSUE THREAD

**Issue by liujason** [google/web-starter-kit#831]
To reproduce:
uncomment `https:true` in gulp.task `serve:dist`. 
run `gulp serve:dist`, that also generates a self-signed certificate. 
open browser and use localhost or 127.0.0.1 to the site, and generates the following console error:

> 
GET https://127.0.0.1:3001/service-worker.js net::ERR_INSECURE_RESPONSE
main.js:78 
Error during service worker registration: DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.(anonymous function) @ main.js:78

**Comment by surma** [comment]
That is more or less working as expected. Service worker work on `localhost` without TLS so there really is no reason for you to turn it on if it’s SW you are after.

This option is mainly there to check for mixed-content warning and as the comment in the `gulpfile` states, a self-signed certificate will cause a certificate error. If you want to test your SW with TLS on localhost, generate your own self-signed certificate and add it your system’s trusted certificate list.

```JS
gulp.task('serve', ['scripts', 'styles'], () => {
  browserSync({
    // ...
    https: {
      key: 'path/to/cert.key',
      cert: 'path/to/cert.pem'
    },
    // ...
  });
```

**Comment by QiQi57** [comment]
I have the same problem, have you get the solution??? It can work with the localhost host name but I want to test it in my mobile. So the host name should be IP address or custom host string.
