### ISSUE TITLE
What about stylus support ?

### ISSUE THREAD

**Issue by Woogyloaf** [google/web-starter-kit#834]

**Comment by surma** [comment]
What would you like to see, @Woogyloaf? I can’t quite follow, as `web-starter-kit` is a, well, starter kit for your web apps. If you want to support a stylus as your input device, it’s your app’s responsibility to run the appropriate code.

**Comment by robwierzbowski** [comment]
I believe he might be requesting the Stylus CSS preprocessor?

If so, probably a won't add. WSK supports one tool for each job (to stay
manageable by the maintainers and easy to understand for new users). But,
it should be very easy to switch out the Sass plugin with Stylus on your
own.

On Wednesday, February 17, 2016, Surma <notifications@github.com> wrote:

> What would you like to see, @Woogyloaf <https://github.com/Woogyloaf>? I
> can’t quite follow, as web-starter-kit is a, well, starter kit for your
> web apps. If you want to support a stylus as your input device, it’s your
> app’s responsibility to run the appropriate code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/web-starter-kit/issues/834#issuecomment-185094834>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by surma** [comment]
Oh, ha, I didn’t not think about the Stylus preprocessor.

But I agree with what @robwierzbowski said.

**Comment by Woogyloaf** [comment]
Sorry for not being clear enough. I mean Stylust CSS  >> http://stylus-lang.com/ this is amazing tool !

Here is evolution
Less > Sass > Stylus
