### ISSUE TITLE
critical path

### ISSUE THREAD

**Issue by fx3O2** [google/web-starter-kit#838]
Is there any reason, not to include [critical path](https://github.com/addyosmani/critical) by default? It is as essential as uncss and even pagespeed complains about most of the time.

**Comment by surma** [comment]
PSI complains about loading resources in a blocking manner. That is related to this, but definitely not the same thing. [loadCSS](https://github.com/filamentgroup/loadCSS) would a simpler solution to make PSI happy.

@addyosmani’s `critical-path` is a tool to determine which of your styles belong to the critical path. It is not 100% reliable in terms of producing the minimum necessary CSS. Critical styles are highly app dependent and can only really be done right by a developer. I don’t think `critical-path` is always the right choice so I’d rather not include it.

@gauntface WDYT?

**Comment by robwierzbowski** [comment]
Agree. Programatic methods of determining critical path CSS aren't reliable
in a JS application, so we shouldn't include.

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by gauntface** [comment]
+1 @surma comment regarding it not being 100% reliable and I think developers will be lost / confused by.

If you are at a stage where you are looking at supporting this, you'd pick the best route and add it yourself.

(i.e. organisation of Sass vs tooling to automatically manage it)

**Comment by fx3O2** [comment]
When you talk about an **app**, do you only think of those common single-page applications everyone is so excited about? Am I wrong using web-starter-kit for content related sites, e.g. driven by a CMS?

**Comment by surma** [comment]
The distinction doesn’t really matter in this case. If you care about above-the-fold styles, you effectively made your first step towards being an app already ;)
