### ISSUE TITLE
MDL: Why do you have to reference the same set of source files twice?

### ISSUE THREAD

**Issue by glumanda99** [google/web-starter-kit#842]
According to: https://github.com/google/web-starter-kit/blob/master/docs/mdl-sass.md

> Note: We are aware that it can feel a little suboptimal to reference the same set of source files twice in the above pipeline. We wil be looking at simplifying this workflow in a future release.

Why do you have to define the same sources in the hdml build block and in the gulp src? I thought useref would handle all that stuff.

**Comment by vorburger** [comment]
https://github.com/google/web-starter-kit/issues/913 is somewhat related to this.

**Comment by gauntface** [comment]
I'm hoping to move away from MDL and simplify the build process at which point this will no longer be relevant. See #940 to comment or for more info.
