### ISSUE TITLE
gulp serve not working as expected

### ISSUE THREAD

**Issue by m2mathew** [google/web-starter-kit#854]
I forked the repo, did the `npm install`, and ran `gulp serve`. It appears that the ES2015 syntax is throwing the errors. As I change the `const` to `var`, then it starts to get rid of the issues.

Is there a way to leave in the ES2015 syntax and use the gulpfile as is?

Bit of a noob at setting up and using some of these tools. Many thanks! :rocket:

**Comment by surma** [comment]
What version of node are you running?

**Comment by m2mathew** [comment]
v5.8.0

**Comment by m2mathew** [comment]
I reinstalled node, deleted `node_modules`, redid the `npm install` - works fine now!
