### ISSUE TITLE
Gulp not copying all my folders and files to dist

### ISSUE THREAD

**Issue by cspwcspw** [google/web-starter-kit#863]
I'm a noob, both for WSK and gulp, so it might just be something trivial.   gulp CLI 3.9.1 local version 3.9.1, on Windows 10.  I'm using gulpfile.babel.js directly from the WSK 0.6.1

I've moved an existing web site to WSK.  In my app I have subfolders, say /games/sudoku.  In that folder I have only two assets - a zip file and a png.   
Unless I add an html file into the folder, the folder doesn't even get created in the dist.   And if I do add a dummy html file in the folder, the folder gets created and the html file gets copied to dist, but not the other assets. 
The assets are referenced from links in my app's index.html page, (so the dist site is broken on these links).   The  gulp serve version runs just fine locally.

1) If I were to deploy from the app directory to my web site, is there a risk that I might NOT get something that gulp might have added to dist behind my back? 

2) Any suggestions or ways I can tell gulp to "copy these folder structures verbatim".

Thanks
Peter

**Comment by cspwcspw** [comment]
We can close this, thanks.  I read a bit about gulp and understood what I had to do.

**Comment by gantner** [comment]
Please consider posting your solution as people will find this via google but not learn a solution.

**Comment by anjunatl** [comment]
@gantner Do you happen to remember what the solution was? The link you provided is dead now. Thanks!

**Comment by gantner** [comment]
@anjunatl - yes the link moved. here is the current location: http://opnsrce.github.io/how-to-make-gulp-copy-a-directory-and-its-contents
