### ISSUE TITLE
Feature: Swap out Gulp for a Module Bundler

### ISSUE THREAD

**Issue by TheLarkInn** [google/web-starter-kit#880]
Is it really best to be promoting the use of Gulp as a processor of JS files optimized for the web?

Unless the use of babel is helping to remove duplicate file dependencies, assisting in supporting long term caching, etc. (Which it didn't _appear_ that was the case), then it would be probably best to instead start promoting the use of one of the many Module Bundlers that are currently available. 

There is webpack, browserify, Rollup(a better optimized bundle however less out of the tool features compared to webpack), or even Brunch. 

All these are great alternatives, in comparison to having a task runner processing files. 

Since I'm on the webpack core team, I am a little biased. However, the webpack team would be more than happy to help you guys make a transition over to it, if it's a path you would like to take! I think overall we should be discouraging the use of grunt/gulp/task runners to "bundle" files. 

Let me know if we can be of assistance!

**Comment by simonlc** [comment]
wsk2 branch is using browserify along with rollupify.

**Comment by gauntface** [comment]
We'll switch to Rollup in the next version encouraging module imports / exports. More info in #940
