### ISSUE TITLE
Update Google Analytics snippet

### ISSUE THREAD

**Issue by bransbury** [google/web-starter-kit#881]
I was looking at the Google Developer site and noticed this starter kit is using the old Google Analytics snippet. For newer browsers the following snippet is recommended:

``` javascript
<!-- Google Analytics -->
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->
```

Source: https://developers.google.com/analytics/devguides/collection/analyticsjs/

This change would involve updating:
- **basic.html** lines 44-49 (https://github.com/google/web-starter-kit/blob/master/app/basic.html#L44-L49) 
  and 
- **index.html** lines 293-298 (https://github.com/google/web-starter-kit/blob/master/app/index.html#L293-L298)

I'm happy to submit a PR if the proposed update is accepted.

**Comment by gauntface** [comment]
Added a note to #940 to fix this.
