### ISSUE TITLE
Example code uses old version of Material Design Lite

### ISSUE THREAD

**Issue by kmturley** [google/web-starter-kit#884]
Web Starter Kit currently uses:

```
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
```

But the official page at:
https://getmdl.io/started/index.html#download

Recommends:

```
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.2.0/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.2.0/material.min.js"></script>
```

The differences are:
- Using versions 1.0.6 but there is now updated version 1.2.0
- Ordering of icons and css is also different. Not sure if that makes a difference.
- Hosted location is different storage.googleapis.com vs code.getmdl.io

**Comment by Garbee** [comment]
We need to wait for a patch to land for 1.2 before upgrading. I'm working on it again today to try and find the full fix to the problem that has shown up.

**Comment by Garbee** [comment]
V 1.2.1 is now tagged, WSK should be updated to use that since it has a critical fix for the drawer toggle icon alignment.

cc @addyosmani

**Comment by mikeerickson** [comment]
@garbee has this happened yet?
