### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Andrew6166** [google/web-starter-kit#896]
There is no particular issue I am having with the web starter kit. There are great components inside it. The problem I am having is that I cannot find any proper documentation on the css classes the kit uses. For example bootstrap has an entire site where you can find a specific component you want and it will show you the css code for it. I need proper documentation in order to do proper development. Is there any proper documentation like bootstrap has for example.

**Comment by sanchezandoni** [comment]
https://google.github.io/web-starter-kit/hello-world/styleguide.html

**Comment by Andrew6166** [comment]
Will have a look at that thanks

**Comment by GenericUK** [comment]
That demo version is out of date, MDL (material design lite) has now replaced the styleguide version. I already reported this see issue #893

**Comment by Andrew6166** [comment]
That stuff is exactly what I am looking for Thanks

**Comment by GenericUK** [comment]
https://webdesign.tutsplus.com/tutorials/learning-material-design-lite-the-grid--cms-24531
https://www.tutorialspoint.com/materialdesignlite/materialdesignlite_grids.htm
http://carterrink.com/css/design/2016/01/17/material-design-lite.html
http://tutorialzine.com/2015/07/comparing-bootstrap-with-mdl/

**Comment by GenericUK** [comment]
https://getmdl.io
https://material.google.com

**Comment by Andrew6166** [comment]
wow thanks that really is great. saves me doing research fining that stuff. !!
