### ISSUE TITLE
useref usage is very confusing to any noob

### ISSUE THREAD

**Issue by vorburger** [google/web-starter-kit#913]
Full disclosure: I'm a Web/JS/Gulp/etc. noob (Java background guy), and built my first new web app in too long today. Searched around online and hit web-starter-kit, looked like a useful starting point.

Found it VERY confusing (in current master / rev. 63315d42543a2b82607c27504bdae90f5da8e665), and banged my head against a wall for hours, re. how `useref` is used here... I tried, in vain, to add some more *.JS into the `<!-- build:js scripts/main.min.js -->` block in [app/index.html](https://github.com/google/web-starter-kit/blob/master/app/index.html#L288), wondering why it would only ever minify main.js, but silently drop (!) any JS I would add in the build:js block... ;-)

Ultimately I had a much closer look at the [gulpfile.babel.js](https://github.com/google/web-starter-kit/blob/master/gulpfile.babel.js#L108), learnt that [gulp-useref](https://www.npmjs.com/package/gulp-useref) is the thingie that does this, found things were hard-coded there, and eventually managed to change that.

But is this really necessary? Even if this example starts with just a main.js, why lock it down hard-coded like it is? I would be happy to raise a PR proposing simplifying this and aligning it with how I see you're doing it in the Yeoman generator-webapp - which is where I, eventually, learnt how to "fix" my project based on this web-starter-kit... good learning experience, but perhaps you'd like to avoid others going through this? If there are strong good reasons why this can't just be done like it is in the Yeoman generator-webapp, then at the very least how about a fat warning in the index.html?

**Comment by gauntface** [comment]
Agree with this and would like to remove useref in the next release of WSK: See #940 

While it's nice, the confusion and annoyance of a failing prod build makes me think it's not the right tool for the job. Comments welcome on #940.
