### ISSUE TITLE
Unusable due to corruption of Index.html by nonsense Latin phrases

### ISSUE THREAD

**Issue by Avonstar** [google/web-starter-kit#927]
Hi, I am following the "Your first Progressive Web App tutorial". There was a recommendation to download the Web-Starter Kit. However it is unusable as there are nonsense Latin characters in the Index.html file. e.g. 
<h4>Features</h4>
              Minim duis incididunt est cillum est ex occaecat consectetur. Qui sint ut et qui nisi cupidatat. Reprehenderit nostrud proident officia exercitation anim et pariatur ex.
              <ul class="toc">
                <h4>Contents</h4>
                <a href="#lorem1">Lorem ipsum</a>
                <a href="#lorem2">Lorem ipsum</a>
                <a href="#lorem3">Lorem ipsum</a>
                <a href="#lorem4">Lorem ipsum</a>
                <a href="#lorem5">Lorem ipsum</a>
              </ul>

**Comment by Garbee** [comment]
Can you please define "unusable"? This is just standard Lorem Ipsum filler text. It's just text, no special latin characters.

**Comment by Avonstar** [comment]
Hi Garbee I misunderstood. I don't really understand how to use these tools. Need to read up more. Thanks. Will close the issue.
