### ISSUE TITLE
Current state of project

### ISSUE THREAD

**Issue by Toshakins** [google/web-starter-kit#956]
I saw [a deprecation warning](https://developers.google.com/web/tools/starter-kit/) at the documentation page. As I understand, there are no longer plans from the Google site to support WSK project. 

What is the rationale behind this decision? Additionally, are there any recommendations what to use as a replacement?

**Comment by Garbee** [comment]
Ref #940 for the discussion on the projects possible future. I haven't heard anything too concrete one way or the other yet. I think it will come down to how much time there is to continue maintaining it with everything else going on.

**Comment by Toshakins** [comment]
@Garbee Thanks, missed that issue. Closing this as question resolved(seems people switched to [Workbox](https://workboxjs.org/)).
