### ISSUE TITLE
Why is the Web Starter Kit no longer supported and what has replaced it?

### ISSUE THREAD

**Issue by evanp** [google/web-starter-kit#958]
[This page](https://developers.google.com/web/tools/starter-kit/) says "Warning: Web Starter Kit is no longer supported." Why not? What has replaced it, if anything?

If nothing, who is going to fork this repo and continue this development?

**Comment by Garbee** [comment]
Reference #940

**Comment by gauntface** [comment]
@evanp there is enough of a desire that I think we'll try and bring WSK back down to a more self maintaining mode - if you'd be up for helping, I would :heart: input and help on the doc links in #940
