### ISSUE TITLE
jarroddeming@gmail.com

### ISSUE THREAD

**Issue by JarrodDeming** [google/web-starter-kit#974]

**Comment by JarrodDeming** [comment]
Cannot bypass 2-step Verification for my Google account can not log in

**Comment by Garbee** [comment]
I understand that you've been locked out of your account and would like some assistance in recovering it. However, Google Account Recovery has nothing to do with this project from Developer Relations. No one working on any of the Github projects can help you with this issue. Account Recovery is a completely different department and they have their own rules to follow from the legal department.

These issues and opening/closing them is not going to achieve anything. Your only option is to follow the account recovery process. If you are unable to complete that successfully, then unfortunately you have lost access to your account. I'm sorry of this is new information to you, I do understand the pain. I myself am locked out of numerous accounts I wish I had access to from years past. Nothing makes it easier, but at some point you do your best to move on.
