### ISSUE TITLE
2 step verification code change phone number jarroddeming@gmail.com 

### ISSUE THREAD

**Issue by JarrodDeming** [google/web-starter-kit#975]

**Comment by JarrodDeming** [comment]
@jarroddeming

**Comment by JarrodDeming** [comment]
I can not bypass 2-step varcison

**Comment by Garbee** [comment]
My comment in #974 applies just the same here. Please don't duplicate issues and cause more notifications to those watching to go out. It's just an annoyance.

**Comment by JarrodDeming** [comment]
<details><summary>Details</summary>
<p>

@JarrodDeming 

</p>
</details>
